### ISSUE TITLE
Flaky error core/mountpoint/test_winfstest.py::test_winfstest[08_CreateFile_Delete.t]

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1131]
https://dev.azure.com/Scille/parsec/_build/results?buildId=487&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=1b8d0bba-f11a-562f-077c-1aaa5fdf35ee&l=75

```python
tests/core/mountpoint/test_winfstest.py::test_winfstest[08_CreateFile_Delete.t] FAILED [ 96%]

================================== FAILURES ===================================
___________________ test_winfstest[08_CreateFile_Delete.t] ____________________
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\winfspy\tests\winfstest\test_winfs.py", line 180, in create_directory
    win32file.CreateDirectory(path, security_attributes)
pywintypes.error: (183, 'CreateDirectory', 'Cannot create a file when that file already exists.')
"""

The above exception was the direct cause of the following exception:

test_module_path = WindowsPath('c:/hostedtoolcache/windows/python/3.6.8/x64/lib/site-packages/winfspy/tests/winfstest/cases/08_CreateFile_Delete.t')
file_system_path = WindowsPath('C:/Users/VssAdministrator/AppData/Local/Temp/pytest-of-VssAdministrator/pytest-1/test_winfstest_08_CreateFile_D0/mountpoint-svc-1/w')
process_runner = <function process_runner.<locals>.runner at 0x00000229EB75E378>

    @pytest.mark.slow
    @pytest.mark.mountpoint
    @pytest.mark.parametrize("test_module_path", TEST_MODULES, ids=[path.name for path in TEST_MODULES])
    def test_winfstest(test_module_path, file_system_path, process_runner):
    
        # File attributes are not supported at the moment
        if "CreateFile_Attributes" in test_module_path.name:
            pytest.xfail()
    
        # Does not pass because of strict attribute testing
        if "CreateRemoveDirectory" in test_module_path.name:
            pytest.xfail()
    
        # Read-only attribute is required for the MoveFile test case
        if "MoveFile" in test_module_path.name:
            pytest.xfail()
    
        # Setting file attributes is not supported at the moment
        if "SetGetFileAttributes" in test_module_path.name:
            pytest.xfail()
    
        # Setting file times is not supported at the moment
        if "FileTime" in test_module_path.name:
            pytest.xfail()
    
        # Setting security attributes is not supported at the moment
        if "GetSetSecurity" in test_module_path.name:
            pytest.xfail()
    
        # Run winfstest with the parsec mountpoint
>       winfstest.test_winfs(test_module_path, file_system_path, process_runner)

tests\core\mountpoint\test_winfstest.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\winfspy\tests\winfstest\test_winfs.py:452: in test_winfs
    exec(test_module, globs)
<string>:28: in <module>
    ???
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\winfspy\tests\winfstest\test_winfs.py:349: in expect
    result = runner(operation, *args, **kwargs)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\winfspy\tests\winfstest\test_winfs.py:425: in runner
    return executor.submit(fn, *args, **kwargs).result()
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\concurrent\futures\_base.py:432: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Future at 0x229ee5d0c18 state=finished raised error>

    def __get_result(self):
        if self._exception:
>           raise self._exception
E           pywintypes.error: (183, 'CreateDirectory', 'Cannot create a file when that file already exists.')

c:\hostedtoolcache\windows\python\3.6.8\x64\lib\concurrent\futures\_base.py:384: error
----------------------------- Captured log setup ------------------------------
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:03[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mfs.entry.updated[0m [36mid[0m=[35mEntryID('d830c448-0d0d-4349-8b37-880c8d72894a')[0m
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:03[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mfs.workspace.created[0m [36mnew_entry[0m=[35mWorkspaceEntry(name='w', id=EntryID('290b185e-92d5-45d3-b473-8a3e610cdd6c'), key=<parsec.crypto.SecretKey object at 0x229eca5eb70>, encryption_revision=1, encrypted_on=<Pendulum [2020-04-19T19:20:03.212604+00:00]>, role_cached_on=<Pendulum [2020-04-19T19:20:03.212604+00:00]>, role=<RealmRole.OWNER: 'OWNER'>)[0m
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:03[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mmountpoint.starting[0m [36mmountpoint[0m=[35mWindowsPath('C:/Users/VssAdministrator/AppData/Local/Temp/pytest-of-VssAdministrator/pytest-1/test_winfstest_08_CreateFile_D0/mountpoint-svc-1/w')[0m
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:03[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mmountpoint.started[0m [36mmountpoint[0m=[35mWindowsPath('C:/Users/VssAdministrator/AppData/Local/Temp/pytest-of-VssAdministrator/pytest-1/test_winfstest_08_CreateFile_D0/mountpoint-svc-1/w')[0m
---------------------------- Captured stdout call -----------------------------
Running test module 08_CreateFile_Delete.t:

#!/usr/bin/python

# STATUS_DELETE_PENDING
# FindFiles with delete pending

from winfstest import *

name = uniqname()

with expect_task(
    "CreateFile %s GENERIC_WRITE FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0"
    % name,
    0,
):
    expect(
        "CreateFile %s GENERIC_READ FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0"
        % name,
        0,
    )
    expect("DeleteFile %s" % name, 0)
    # STATUS_DELETE_PENDING translated to ERROR_ACCESS_DENIED below
    expect(
        "CreateFile %s GENERIC_READ FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0"
        % name,
        "ERROR_ACCESS_DENIED",
    )

expect("CreateDirectory %s 0" % name, 0)
with expect_task(
    "CreateFile %s\\foo GENERIC_WRITE FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0"
    % name,
    0,
):
    expect("DeleteFile %s\\foo" % name, 0)
    e, r = expect("FindFiles %s\\*" % name, 0)
    s = set(l["FileName"] for l in r)
    testeval(len(s) == 3)
    testeval("." in s)
    testeval(".." in s)
    testeval("foo" in s)
e, r = expect("FindFiles %s\\*" % name, 0)
s = set(l["FileName"] for l in r)
testeval(len(s) == 2)
testeval("." in s)
testeval(".." in s)
expect("RemoveDirectory %s" % name, 0)

testdone()


** Running command:
-> CreateFile %s\559d0282-cbd4-4e86-bcd2-5ccd77f98d1b GENERIC_WRITE FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0
-> Expecting a handle to keep open
-> Keeping <PyHANDLE:2740> open
** Running command:
-> CreateFile %s\559d0282-cbd4-4e86-bcd2-5ccd77f98d1b GENERIC_READ FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0
-> Expecting: None
-> Got: None
** Running command:
-> DeleteFile %s\559d0282-cbd4-4e86-bcd2-5ccd77f98d1b
-> Expecting: None
-> Got: None
** Running command:
-> CreateFile %s\559d0282-cbd4-4e86-bcd2-5ccd77f98d1b GENERIC_READ FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0
-> Expecting: ERROR_ACCESS_DENIED
-> Got: errno=5, message='Access is denied.'
** Closing: <PyHANDLE:2740>
** Running command:
-> CreateDirectory %s\559d0282-cbd4-4e86-bcd2-5ccd77f98d1b 0
-> Expecting: None
------------------------------ Captured log call ------------------------------
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:03[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mfs.entry.updated[0m [36mid[0m=[35mEntryID('290b185e-92d5-45d3-b473-8a3e610cdd6c')[0m [36mworkspace_id[0m=[35mEntryID('290b185e-92d5-45d3-b473-8a3e610cdd6c')[0m
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:03[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mfs.entry.updated[0m [36mid[0m=[35mEntryID('6e8b87b2-3c38-4fbe-a087-618c88a9901f')[0m [36mworkspace_id[0m=[35mEntryID('290b185e-92d5-45d3-b473-8a3e610cdd6c')[0m
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:04[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mfs.entry.updated[0m [36mid[0m=[35mEntryID('290b185e-92d5-45d3-b473-8a3e610cdd6c')[0m [36mworkspace_id[0m=[35mEntryID('290b185e-92d5-45d3-b473-8a3e610cdd6c')[0m
---------------------------- Captured log teardown ----------------------------
event_bus.py                49 DEBUG    [2m2020-04-19 19:20:04[0m [[32m[1mdebug    [0m] [1mSend event                    [0m [[34m[1mparsec.event_bus[0m] [36mevent_name[0m=[35mmountpoint.stopped[0m [36mmountpoint[0m=[35mWindowsPath('C:/Users/VssAdministrator/AppData/Local/Temp/pytest-of-VssAdministrator/pytest-1/test_winfstest_08_CreateFile_D0/mountpoint-svc-1/w')[0m
------ generated xml file: d:\a\_temp\empty\test-results-mountpoint.xml -------


========================== slowest 10 test durations ==========================
67.09s call     tests/core/mountpoint/test_folder_operations.py::test_folder_operations
36.63s call     tests/core/mountpoint/test_base.py::test_mountpoint_iterdir_with_many_files[/foo-1000]
33.22s call     tests/core/mountpoint/test_base.py::test_mountpoint_iterdir_with_many_files[/-1000]
31.85s call     tests/core/mountpoint/test_file_operations.py::test_file_operations
1.71s call     tests/core/mountpoint/test_winfstest.py::test_winfstest[00_CreateFile_Dispositions.t]
1.57s call     tests/core/mountpoint/test_winfstest.py::test_winfstest[03_FindFiles.t]
1.52s call     tests/core/mountpoint/test_winfstest.py::test_winfstest[05_CreateFile_Truncation.t]
1.32s call     tests/core/mountpoint/test_winfstest.py::test_winfstest[08_CreateFile_Delete.t]
1.30s call     tests/core/mountpoint/test_base.py::test_mountpoint_iterdir_with_many_files[/foo-100]
1.27s call     tests/core/mountpoint/test_base.py::test_mountpoint_iterdir_with_many_files[/-100]
= 1 failed, 36 passed, 8 skipped, 1038 deselected, 5 xfailed in 199.17 seconds =

##[error]Bash exited with code '1'.
##[section]Finishing: Tests mountpoint
```

**Comment by vxgmichel** [comment]
Moving to #1232
