### ISSUE TITLE
Python 3.8 bug trio_asyncio with postgresql

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1194]
Bug of trio_asyncio with Python 3.8

Example : 
Test of migrate command with an unknow db with python 3.8
python -m parsec.cli backend migrate --db postgresql://localhost:4444
BaseException raised in apply_migrations during the triopg.connect(line 76 in file handler.py).

Working correctly with python 3.7.

**Comment by bitlogik** [comment]
Nous rencontrons le même problème avec 0a7dedff4cc935c2cb352e70f516fd8dee810aef sous Ubuntu 20.04. Ne fonctionne pas et après investigation c’est à cause de Python 3.8. Parsec fonctionne parfaitement avec Python3.6. Une fois le problème identifié, j'ai trouvé ce ticket.

Voici le log avec Python 3.8. :
```
/usr/local/lib/python3.8/dist-packages/trio/_core/_multierror.py:468: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Starting Parsec Backend on 127.0.0.1:9090 (db=POSTGRESQL, blockstore=S3)
2020-06-16 23:00:53 [debug    ] Using selector: _TrioSelector  [asyncio]
/usr/local/lib/python3.8/dist-packages/trio_asyncio/base.py:718: TrioDeprecationWarning: trio.Event.clear is deprecated since Trio 0.12.0; use multiple Event objects or other synchronization primitives instead (https://github.com/python-trio/trio/issues/637)
  self._stopped.clear()
2020-06-16 23:00:53 [debug    ] Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from before-call.apigateway to before-call.api-gateway [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from before-parameter-build.route53 to before-parameter-build.route-53 [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Loading JSON file: /usr/local/lib/python3.8/dist-packages/botocore/data/endpoints.json [botocore.loaders]
2020-06-16 23:00:53 [debug    ] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f69aa2905e0> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Loading JSON file: /usr/local/lib/python3.8/dist-packages/botocore/data/s3/2006-03-01/service-2.json [botocore.loaders]
2020-06-16 23:00:53 [debug    ] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f69aa2e0310> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f69aa86f670> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f69aa2e00d0> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Setting s3 timeout as (60, 60) [botocore.endpoint]
2020-06-16 23:00:53 [debug    ] Loading JSON file: /usr/local/lib/python3.8/dist-packages/botocore/data/_retry.json [botocore.loaders]
2020-06-16 23:00:53 [debug    ] Registering retry handlers for service: s3 [botocore.client]
2020-06-16 23:00:53 [debug    ] Event before-parameter-build.s3.HeadBucket: calling handler <function validate_bucket_name at 0x7f69aa2af160> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-parameter-build.s3.HeadBucket: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f69a9d299a0>> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-parameter-build.s3.HeadBucket: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f69a9d29a60>> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-parameter-build.s3.HeadBucket: calling handler <function generate_idempotent_uuid at 0x7f69aa2a8d30> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-call.s3.HeadBucket: calling handler <function add_expect_header at 0x7f69aa2af4c0> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-call.s3.HeadBucket: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f69a9d299a0>> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-call.s3.HeadBucket: calling handler <function inject_api_version_header_if_needed at 0x7f69aa2b0820> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Making request for OperationModel(name=HeadBucket) with params: {'url_path': '/bucket01', 'query_string': {}, 'method': 'HEAD', 'headers': {'User-Agent': 'Boto3/1.12.34 Python/3.8.2 Linux/5.4.0-31-generic Botocore/1.15.34'}, 'body': b'', 'url': 'https://s3.domain/bucket01', 'context': {'client_region': 'eu', 'client_config': <botocore.config.Config object at 0x7f69aa006640>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'bucket01'}}} [botocore.endpoint]
2020-06-16 23:00:53 [debug    ] Event request-created.s3.HeadBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f69aa006280>> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event choose-signer.s3.HeadBucket: calling handler <function set_operation_specific_signer at 0x7f69aa2a8c10> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Event before-sign.s3.HeadBucket: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f69a9d29af0>> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] Using S3 path style addressing. [botocore.utils]
2020-06-16 23:00:53 [debug    ] Calculating signature using v4 auth. [botocore.auth]
2020-06-16 23:00:53 [debug    ] CanonicalRequest:
HEAD
/bucket01

host:s3.domain
x-amz-content-sha256:REDACTED
x-amz-date:REDACTED

host;x-amz-content-sha256;x-amz-date
REDACTED [botocore.auth]
2020-06-16 23:00:53 [debug    ] StringToSign:
AWS4-HMAC-SHA256
REDACTED
20200616/eu/s3/aws4_request
REDACTED [botocore.auth]
2020-06-16 23:00:53 [debug    ] Signature:
REDACTED [botocore.auth]
2020-06-16 23:00:53 [debug    ] Sending http request: <AWSPreparedRequest stream_output=False, method=HEAD, url=https://s3.domain/bucket01, headers={'User-Agent': b'Boto3/1.12.34 Python/3.8.2 Linux/5.4 Botocore/1.15.34', 'X-Amz-Date': b'REDACTED', 'X-Amz-Content-SHA256': b'REDACTED', 'Authorization': b'AWS4-HMAC-SHA256 Credential=REDACTED/20200616/eu/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED'}> [botocore.endpoint]
2020-06-16 23:00:53 [debug    ] Starting new HTTPS connection (1): s3.domain:443 [urllib3.connectionpool]
2020-06-16 23:00:53 [debug    ] https://s3.domain:443 "HEAD /bucket01 HTTP/1.1" 200 0 [urllib3.connectionpool]
2020-06-16 23:00:53 [debug    ] Response headers: {'Content-Type': 'application/xml', 'Date': 'Tue, 16 Jun 2020 23:00:53 GMT', 'Server': 'S3', 'x-amz-bucket-region': 'eu', 'x-amz-id-2': 'REDACTED', 'x-amz-request-id': 'REDACTED'} [botocore.parsers]
2020-06-16 23:00:53 [debug    ] Response body:
b''             [botocore.parsers]
2020-06-16 23:00:53 [debug    ] Event needs-retry.s3.HeadBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7f69a9d29940> [botocore.hooks]
2020-06-16 23:00:53 [debug    ] No retry needed.               [botocore.retryhandler]
2020-06-16 23:00:53 [debug    ] Event needs-retry.s3.HeadBucket: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f69a9d299a0>> [botocore.hooks]
/usr/local/lib/python3.8/dist-packages/trio_asyncio/base.py:638: TrioDeprecationWarning: trio.open_cancel_scope is deprecated since Trio 0.11.0; use trio.CancelScope instead (https://github.com/python-trio/trio/issues/607)
  with trio.open_cancel_scope() as scope:
/usr/local/lib/python3.8/dist-packages/trio_asyncio/base.py:585: TrioDeprecationWarning: trio.open_cancel_scope is deprecated since Trio 0.11.0; use trio.CancelScope instead (https://github.com/python-trio/trio/issues/607)
  with trio.open_cancel_scope() as scope:
Error: no running event loop
Traceback (most recent call last):
  File "/usr/local/bin/parsec", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/parsec/cli.py", line 44, in patched_cli_main
    return vanilla_cli_main(args=args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/parsec/backend/cli/run.py", line 360, in run_cmd
    trio_run(_run_backend, use_asyncio=True)
  File "/usr/local/lib/python3.8/dist-packages/parsec/utils.py", line 110, in trio_run
    return trio_asyncio.run(async_fn, *args)
  File "/usr/local/lib/python3.8/dist-packages/trio_asyncio/loop.py", line 393, in run
    trio.run(_run_task, proc, args)
  File "/usr/local/lib/python3.8/dist-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.8/dist-packages/trio_asyncio/loop.py", line 391, in _run_task
    return await proc(*args)
  File "/usr/local/lib/python3.8/dist-packages/parsec/backend/cli/run.py", line 339, in _run_backend
    async with backend_app_factory(config=config) as backend:
  File "/usr/local/lib/python3.8/dist-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/usr/local/lib/python3.8/dist-packages/parsec/backend/app.py", line 44, in backend_app_factory
    async with components_factory(config=config, event_bus=event_bus) as components:
  File "/usr/local/lib/python3.8/dist-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/usr/local/lib/python3.8/dist-packages/parsec/backend/postgresql/factory.py", line 37, in components_factory
    await dbh.init(nursery)
  File "/usr/local/lib/python3.8/dist-packages/parsec/backend/postgresql/handler.py", line 162, in init
    self._task_status = await start_task(nursery, self._run_connections)
  File "/usr/local/lib/python3.8/dist-packages/parsec/utils.py", line 102, in start_task
    return await nursery.start(TaskStatus.wrap_task, corofn, *args, name=name)
  File "/usr/local/lib/python3.8/dist-packages/parsec/service_nursery.py", line 183, in start
    return await type(nursery).start(nursery, wrap_child, name=name or async_fn)
  File "/usr/local/lib/python3.8/dist-packages/trio/_core/_run.py", line 952, in start
    old_nursery.start_soon(thunk, *args, name=name)
  File "/usr/local/lib/python3.8/dist-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.8/dist-packages/parsec/service_nursery.py", line 181, in wrap_child
    await async_fn(*args, task_status=task_status)
  File "/usr/local/lib/python3.8/dist-packages/parsec/utils.py", line 89, in wrap_task
    value = await nursery.start(corofn, *args)
  File "/usr/local/lib/python3.8/dist-packages/parsec/service_nursery.py", line 183, in start
    return await type(nursery).start(nursery, wrap_child, name=name or async_fn)
  File "/usr/local/lib/python3.8/dist-packages/trio/_core/_run.py", line 952, in start
    old_nursery.start_soon(thunk, *args, name=name)
  File "/usr/local/lib/python3.8/dist-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.8/dist-packages/parsec/service_nursery.py", line 181, in wrap_child
    await async_fn(*args, task_status=task_status)
  File "/usr/local/lib/python3.8/dist-packages/parsec/backend/postgresql/handler.py", line 165, in _run_connections
    async with triopg.create_pool(
  File "/usr/local/lib/python3.8/dist-packages/triopg/_triopg.py", line 119, in __aenter__
    self._asyncpg_pool = await trio_asyncio.aio_as_trio(
  File "/usr/local/lib/python3.8/dist-packages/trio_asyncio/adapter.py", line 76, in __call__
    return await self.loop.run_aio_coroutine(f)
  File "/usr/local/lib/python3.8/dist-packages/trio_asyncio/base.py", line 229, in run_aio_coroutine
    return await run_aio_future(coro)
  File "/usr/local/lib/python3.8/dist-packages/trio_asyncio/util.py", line 39, in run_aio_future
    res = await trio.hazmat.wait_task_rescheduled(abort_cb)
  File "/usr/local/lib/python3.8/dist-packages/trio/_core/_traps.py", line 165, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/usr/local/lib/python3.8/dist-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
  File "/usr/local/lib/python3.8/dist-packages/trio_asyncio/adapter.py", line 39, in _call_defer
    return await proc(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 426, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1668, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connect_utils.py", line 652, in _connect
    con = await _connect_addr(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connect_utils.py", line 621, in _connect_addr
    tr, pr = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 448, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop

```
Il y a effectivemnt un problème avec Trio en 3.8 : **RuntimeError: no running event loop** , éventuellement masqué par un problème de exception handler (_You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks._)

Un des problèmes sur les versions est que les pipelines de tests ne sont que en Python 3.6, et donc il faudra logiquement soit restreindre l'utilisation de parsec à cette version de Python, ou bien tester avec les autres versions (3.7 et 3.8).

Et pour ce problème de trio : des pistes ici :
https://github.com/python-trio/trio-asyncio/issues/63

**Solution** probable : Mettre à jour trio-asyncio==0.11.0, cela semble corrigé dans cette version : "fixing support for Python 3.8". Et cela devrait régler les warnings "TrioDeprecationWarning".

**Comment by bitlogik** [comment]
Our tests confirm that updating trio-asyncio to 0.11.0 is working much better. Can we proceed to a pull request ?
