### ISSUE TITLE
Organisation creation from bootstrap URL

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1199]
With the lastest master (Server and Windows client) 0a7dedff4cc935c2cb352e70f516fd8dee810aef :
The GUI client "could not bootstrap the organization" from a given bootstrap parsec URL from a parsec core create_organization CLI command.
The path is menu "Join an organization", paste bootstrap URL, fill the data fields to bootstrap the organization (username, devicename, and password), then finally click on Bootstrap the organization button.

```
{"event": "Starting UI", "logger": "parsec.core.gui.app", "level": "info", "timestamp": "2020-06-17 10:45:18"}
{"event": "No language in settings, trying local language 'en'", "logger": "parsec.core.gui.lang", "level": "info", "timestamp": "2020-06-17 10:45:18"}
{"port": 51525, "event": "IPC server ready", "logger": "parsec.core.ipcinterface", "level": "info", "timestamp": "2020-06-17 10:45:19"}
{"task_name": "parsec.core.gui.trio_thread.QtToTrioJob._run_fn", "total_time": 0.344, "cpu_time": 0.094, "io_time": 0.25, "stack_before": "", "stack_after": "  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\service_nursery.py\", line 181, in wrap_child\n    await async_fn(*args, task_status=task_status)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\trio_thread.py\", line 94, in _run_fn\n    result = await self._fn(*self._args, **self._kwargs)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\new_version.py\", line 35, in _do_check_new_version\n    resolved_url = (await _async_get(url, method=\"HEAD\")).geturl()\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\new_version.py\", line 30, in _async_get\n    return await trio.to_thread.run_sync(lambda: urlopen(Request(url, method=method)))\n", "event": "Blocking IO detected", "logger": "parsec.monitoring", "level": "warning", "timestamp": "2020-06-17 10:45:19"}
{"event": "Uncatched error", "logger": "parsec.core.gui.trio_thread", "level": "exception", "exception": "Traceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\trio_thread.py\", line 94, in _run_fn\n    result = await self._fn(*self._args, **self._kwargs)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\bootstrap_organization_widget.py\", line 84, in _do_bootstrap_organization\n    device_certificate,\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\expose_cmds.py\", line 15, in wrapper\n    return await cmd(transport, *args, **kwargs)\nTypeError: organization_bootstrap() missing 2 required positional arguments: 'redacted_user_certificate' and 'redacted_device_certificate'", "timestamp": "2020-06-17 10:50:33"}
Traceback (most recent call last):
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\trio_thread.py", line 94, in _run_fn
    result = await self._fn(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\bootstrap_organization_widget.py", line 84, in _do_bootstrap_organization
    device_certificate,
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\expose_cmds.py", line 15, in wrapper
    return await cmd(transport, *args, **kwargs)
TypeError: organization_bootstrap() missing 2 required positional arguments: 'redacted_user_certificate' and 'redacted_device_certificate'
{"event": "Uncatched error", "logger": "parsec.core.gui.trio_thread", "level": "exception", "exception": "Traceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\trio_thread.py\", line 94, in _run_fn\n    result = await self._fn(*self._args, **self._kwargs)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\bootstrap_organization_widget.py\", line 84, in _do_bootstrap_organization\n    device_certificate,\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\expose_cmds.py\", line 15, in wrapper\n    return await cmd(transport, *args, **kwargs)\nTypeError: organization_bootstrap() missing 2 required positional arguments: 'redacted_user_certificate' and 'redacted_device_certificate'", "timestamp": "2020-06-17 10:50:39"}
Traceback (most recent call last):
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\trio_thread.py", line 94, in _run_fn
    result = await self._fn(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\bootstrap_organization_widget.py", line 84, in _do_bootstrap_organization
    device_certificate,
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\expose_cmds.py", line 15, in wrapper
    return await cmd(transport, *args, **kwargs)
TypeError: organization_bootstrap() missing 2 required positional arguments: 'redacted_user_certificate' and 'redacted_device_certificate'
```

Looks like, the GUI didn't even contact the server, because of this breaking change about organization_bootstrap arguments.

Also, the Windows GUI client creates locally the user data. So at next parsec startup, it asks for the user login, then can't connect to server. "Failed to retrieve user list from the server", "Disconnected". It shouldn't create anything locally if the bootstrap (or join) is not successful.

**Comment by bitlogik** [comment]
Here's the create_organisation command used before the GUI bootstrap
```
$ parsec core create_organization MyCompany -B parsec://parsec.server -T AdminToken
/usr/local/lib/python3.8/dist-packages/trio/_core/_multierror.py:468: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Creating organization in backend ✔
Bootstrap organization url: parsec://parsec.server/MyCompany?action=bootstrap_organization&token=f89afcecff1c244d11e4005483ed3d0053b4146dd7ceaa58cd468a162148155d

```

**Comment by touilleMan** [comment]
Thanks for reporting this !

As you may have seen, next release will contain a big improvement on the invitation system (see #1119) and paved the way for user with a limited view on the organization (see #1144)

Long story short, the API between the backend and the core is done, but the GUI is still under work (see #1158). You just got bitten by this ;-)

Until this is fixed, I advice you to use the cli to do user/device invitation and organization bootstrap:
```
$ parsec core bootstrap_organization "parsec://localhost:6777/MyCompany?action=bootstrap_organization&token=5e6830a9941b730e0b96d84b99b9d652a0768e5e3377b6cfce7c0a0f9c043f87&no_ssl=true"
Choose a password for the device:
Repeat for confirmation:
User fullname: John Doe
User email: john.doe@example.com
Device label [gigabite]: pc1
Bootstrapping organization in the backend ✔
Saving device b1c32839f729942b21d4a4b279a4d9dcf6f8af17eb2304d441f56a37ba396807 ✔

$ parsec core list_devices
Found 1 device(s) in C:\Users\gbleu\AppData\Roaming\parsec\config:
b1c - MyCompany: John Doe <john.doe@example.com> @ pc1
```

**Comment by bitlogik** [comment]
Thanks. Following this, the user name and organization name are not displayed after login in the GUI, but replaced by an ID.

![image](https://user-images.githubusercontent.com/32455462/85038217-a0384e00-b186-11ea-93f4-654802e5c45e.png)

Same on the device page, the device name is a hex string.

In the File history : On xx by USERIDHEX@DEVICEIDHEX
Share the workspace : user is given as hex chain

That is that everywhere where I expect the user name or the device name, they are replaced by their respective hex string (a kind of hash, or binary data in hex). Except on the GUI login screen, where the info are correctly displayed.

Here the CLI of the registration :
```
Choose a password for the device:
Repeat for confirmation:
User fullname: Myname
User email: my.name@domain.fr
Device label [DESKTOPX]: PCW10
Bootstrapping organization in the backend ⠙[2m2020-06-18 15:01:04[0m [[33m[1mwarning  [0m] [1mHeavy CPU usage detected      [0m [[34m[1mparsec.monitoring[0m] [36mcpu_time[0m=[35m0.281[0m [36mio_time[0m=[35m0.0[0m [36mstack_after[0m=[35m  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\cli\bootstrap_organization.py", line 25, in _bootstrap_organization
    cmds=cmds, human_handle=human_handle, device_label=device_label
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\invite\organization.py", line 62, in bootstrap_organization
    redacted_device_certificate=redacted_device_certificate,
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\expose_cmds.py", line 14, in wrapper
    async with self.acquire_transport() as transport:
  File "C:\Program Files (x86)\Parsec\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\apiv1_annonymous.py", line 54, in _acquire_transport
    await _init_transport()
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\apiv1_annonymous.py", line 40, in _init_transport
    transport = await apiv1_connect(addr, keepalive=keepalive)
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 81, in apiv1_connect
    return await _connect(addr.hostname, addr.port, addr.use_ssl, keepalive, handshake)
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 124, in _connect
    transport = await Transport.init_for_client(stream, host=hostname)
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\api\transport.py", line 106, in init_for_client
    await transport._net_send(Request(host=host, target="/ws"))
  File "C:\Program Files (x86)\Parsec\site-packages\parsec\api\transport.py", line 91, in _net_send
    await self.stream.send_all(self.ws.send(wsmsg))
[0m [36mstack_before[0m=[35m[0m [36mtask_name[0m=[35mparsec.core.cli.bootstrap_organization._bootstrap_organization[0m [36mtotal_time[0m=[35m0.281[0m
Bootstrapping organization in the backend ✔
Saving device a735571bc77307e798e0310b58a31ec96619d7a0041d24588a2690fe6c36edb6 ✔

parsecCLI list_devices
Found 1 device(s) in C:\Users\ME\AppData\Roaming\parsec\config:
a73 - BitLogiK: MyName <my.name@domain.fr> @ PCW10
```

Note that the device is identified by a different hash in the CLI which is shorter : "622ccdecaf334...." at the device name locations. Probably because the GUI shows UUID and the device hash presented at the of organization bootstrap is the device id "below".

I think this is related to this  https://github.com/Scille/parsec-cloud/commit/0a7dedff4cc935c2cb352e70f516fd8dee810aef or APIv 1.2, and this is like the "decoding" is not working.
Or maybe the corresponding table will be managed by the GUI, and since it was created by CLI aside, it is normal?

**Comment by bitlogik** [comment]
Partially fixed by https://github.com/Scille/parsec-cloud/pull/1211, as this fixes the second issue about names display.

**Comment by bitlogik** [comment]
I tested the latest master, and #1211 didn't fix at all the issue about names display. What is supposed to fix this issue about "human handle" display in GUI ? Or #1211 was just about the API and nothing related with the GUI ?

**Comment by touilleMan** [comment]
Yep, PR #1158 should fix this ;-)

**Comment by Max-7** [comment]
Everything should work fine now on the master branch. Once #1254 is merged you will also be able to create an organization directly from the GUI using a custom backend.
