### ISSUE TITLE
Can not delete invitation in the gui

### ISSUE THREAD

**Issue by AntoineDupre** [Scille/parsec-cloud#1271]
Delete a pending invitation raise the following error: 

```
Traceback (most recent call last):
  File "/home/antdup/parsec-cloud/parsec/core/gui/trio_thread.py", line 94, in _run_fn
    result = await self._fn(*self._args, **self._kwargs)
  File "/home/antdup/parsec-cloud/parsec/core/gui/users_widget.py", line 173, in _do_cancel_invitation
    await core.delete_invitation(token=token)
TypeError: delete_invitation() missing 1 required positional argument: 'reason'
Traceback (most recent call last):
  File "/home/antdup/parsec-cloud/parsec/core/gui/trio_thread.py", line 94, in _run_fn
    result = await self._fn(*self._args, **self._kwargs)
  File "/home/antdup/parsec-cloud/parsec/core/gui/users_widget.py", line 173, in _do_cancel_invitation
    await core.delete_invitation(token=token)
TypeError: delete_invitation() missing 1 required positional argument: 'reason'
```

**Comment by AntoineDupre** [comment]
merged
