### ISSUE TITLE
Moving a file from a workspace to root causes a crash

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#140]
Steps to reproduce:
```console
$ source misc/run_test_environment.sh
[...]
$ DEBUG= parsec core run -P test -D corp:alice@laptop
[...]
# In a new terminal
$ touch ~/parsec_mnt/alice@laptop/alice_workspace/test            
$ mv ~/parsec_mnt/alice@laptop/alice_workspace/test ~/parsec_mnt/alice@laptop
```
The `mv` command is expected to fail since it is not allowed to have a file in the root directory.

Instead, the `parsec core run` instance crashes with the following trace:
```
Error: 
Traceback (most recent call last):
  File "/home/vinmic/miniconda/envs/parsec/bin/parsec", line 11, in <module>
    load_entry_point('parsec-cloud', 'console_scripts', 'parsec')()
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vinmic/parsec-cloud/parsec/core/cli/utils.py", line 67, in wrapper
    return fn(**kwargs)
  File "/home/vinmic/parsec-cloud/parsec/core/cli/utils.py", line 123, in wrapper
    return fn(**kwargs)
  File "/home/vinmic/parsec-cloud/parsec/core/cli/run.py", line 45, in run_mountpoint
    trio.run(_run_mountpoint, config, device, mountpoint)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/trio/_core/_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "/home/vinmic/parsec-cloud/parsec/core/cli/run.py", line 32, in _run_mountpoint
    await trio.sleep_forever()
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/vinmic/parsec-cloud/parsec/core/logged_core.py", line 110, in logged_core_factory
    await mountpoint_manager.teardown()
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/trio/_core/_run.py", line 397, in __aexit__
    raise combined_error_from_nursery
  File "/home/vinmic/parsec-cloud/parsec/core/sync_monitor.py", line 133, in monitor_sync
    await sync_monitor.run(task_status=task_status)
  File "/home/vinmic/parsec-cloud/parsec/core/sync_monitor.py", line 57, in run
    await self._monitoring()
  File "/home/vinmic/parsec-cloud/parsec/core/sync_monitor.py", line 71, in _monitoring
    await self._monitoring_loop()
  File "/home/vinmic/parsec-cloud/parsec/core/sync_monitor.py", line 95, in _monitoring_loop
    await self._monitoring_tick(updated_entries)
  File "/home/vinmic/parsec-cloud/parsec/core/sync_monitor.py", line 116, in _monitoring_tick
    await self.fs.sync_by_id(id)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/fs.py", line 170, in sync_by_id
    await self._load_and_retry(self._syncer.sync_by_id, entry_id)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/fs.py", line 59, in _load_and_retry
    return await fn(*args, **kwargs)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/sync_base.py", line 92, in sync_by_id
    await self._sync_nolock(path, recursive=True)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/sync_base.py", line 134, in _sync_nolock
    await self._sync_folder(path, access, manifest, recursive)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/folder_syncer.py", line 125, in _sync_folder
    await self._sync_nolock(child_path, True)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/sync_base.py", line 115, in _sync_nolock
    need_more_sync = await self._resolve_placeholders_in_path(path, access, manifest)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/sync_base.py", line 156, in _resolve_placeholders_in_path
    need_more_sync = await self._minimal_sync_file(path, access, manifest)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/file_syncer.py", line 275, in _minimal_sync_file
    await self._sync_file_actual_sync(path, access, minimal_manifest)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/file_syncer.py", line 194, in _sync_file_actual_sync
    notify_beacons = self.local_folder_fs.get_beacon(path)
  File "/home/vinmic/parsec-cloud/parsec/core/fs/local_folder_fs.py", line 145, in get_beacon
    assert is_workspace_manifest(manifest)
AssertionError
```

It seems like a check is missing in `LocalFolderFS._copy` (`parsec/core/fs/local_folder_fs.py`).

**Comment by touilleMan** [comment]
close by #150
