### ISSUE TITLE
Windows uninstaller doesn't seems to uninstall everything (crash with 1.8 -> 2.1 update)

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#1536]
```
Traceback (most recent call last):
  File "D:\Programmes\Parsec\site-packages\parsec\cli.py", line 12, in <module>
    from parsec.core.cli import core_cmd
  File "D:\Programmes\Parsec\site-packages\parsec\core\cli\__init__.py", line 5, in <module>
    from parsec.core.cli import list_devices, status_organization
  File "D:\Programmes\Parsec\site-packages\parsec\core\cli\list_devices.py", line 9, in <module>
    from parsec.core.cli.utils import format_available_devices
  File "D:\Programmes\Parsec\site-packages\parsec\core\cli\utils.py", line 11, in <module>
    from parsec.core.local_device import (
ImportError: cannot import name 'AvailableDevice'
```

contenu du dossier parsec.core après désinstallation de la version 1.8
```
d-----       26/10/2020     11:38                backend_connection
d-----       26/10/2020     11:38                cli
d-----       26/10/2020     11:38                gui
d-----       22/06/2020     12:38                local_device
d-----       26/10/2020     11:38                __pycache__
-a----       29/04/2020     18:34          15095 invite_claim.py
```

et local_device
```
d-----       22/06/2020     12:38                __pycache__
-a----       29/04/2020     18:34           2994 cipher.py
-a----       29/04/2020     18:34            455 exceptions.py
-a----       29/04/2020     18:34           5866 utils.py
-a----       29/04/2020     18:34            969 __init__.py
```

et site-packages
```
d-----       22/06/2020     12:38                certifi-2020.4.5.1.dist-info
d-----       22/06/2020     12:38                cffi-1.14.0.dist-info
d-----       22/06/2020     12:38                h11-0.9.0.dist-info
d-----       22/06/2020     12:38                idna-2.9.dist-info
d-----       26/10/2020     11:38                nacl
d-----       26/10/2020     11:38                parsec
d-----       22/06/2020     12:38                parsec_cloud-1.13.0.dist-info
d-----       22/06/2020     12:38                PyNaCl-1.2.1.dist-info
d-----       22/06/2020     12:38                pypika
d-----       22/06/2020     12:38                PyPika-0.36.5.dist-info
d-----       26/10/2020     11:38                PyQt5
d-----       22/06/2020     12:38                PyQt5-5.13.1.dist-info
d-----       22/06/2020     12:38                PyQt5_sip-12.7.2.dist-info
d-----       22/06/2020     12:38                pytzdata-2019.3.dist-info
d-----       22/06/2020     12:38                six-1.14.0.dist-info
d-----       22/06/2020     12:38                sortedcontainers-2.1.0.dist-info
d-----       22/06/2020     12:38                tzlocal-2.0.0.dist-info
d-----       22/06/2020     12:38                urllib3-1.25.9.dist-info
d-----       26/10/2020     11:38                winfspy
d-----       22/06/2020     12:38                winfspy-0.7.4.dist-info
```

[Parsec.zip](https://github.com/Scille/parsec-cloud/files/5438340/Parsec.zip)

**Comment by touilleMan** [comment]
fixed by #1690
