### ISSUE TITLE
Can not create new user from invite

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#165]
After inputting the received token and URL, clicking on Register button results in an error dialog box : "Can not create this user" with the following trace :

```
stefan@carbon:~$ parsec
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.parsec', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.parsec', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.parsec', please create it with 0700 permissions.

(process:9489): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
libpng warning: iCCP: known incorrect sRGB profile
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
Traceback (most recent call last):
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/backend_connection/transport.py", line 91, in _do_handshade
    ch.process_result_req(result_req)
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/api/protocole/handshake.py", line 159, in process_result_req
    raise HandshakeFormatError(f"Bad result for `result` handshake: {data['result']}")
parsec.api.protocole.handshake.HandshakeFormatError: Bad result for `result` handshake: bad_format

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/gui/login_widget.py", line 223, in claim_user
    self.line_edit_password.text(),
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/gui/login_widget.py", line 157, in _claim_user
    async with backend_anonymous_cmds_factory(addr) as cmds:
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/backend_connection/porcelain.py", line 113, in backend_anonymous_cmds_factory
    async with anonymous_transport_factory(addr) as transport:
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/backend_connection/transport.py", line 121, in anonymous_transport_factory
    transport = await _connect(addr)
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/backend_connection/transport.py", line 51, in _connect
    await _do_handshade(transport, device_id, signing_key)
  File "/snap/parsec/38/venv/lib/python3.6/site-packages/parsec/core/backend_connection/transport.py", line 103, in _do_handshade
    raise BackendHandshakeError(exc) from exc
parsec.core.backend_connection.exceptions.BackendHandshakeError: Bad result for `result` handshake: bad_format
libpng warning: iCCP: known incorrect sRGB profile
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
```

**Comment by stefan-contiu** [comment]
Fixed using `edge` rather than `stable-0.9.2` snap install.
