### ISSUE TITLE
Too much data for declared Content-Length

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2072]
```
Mar 14 00:51:41 parsec-cloud-prod app/web.1 2022-03-13T23:51:40.633805Z [error    ] Unexpected crash               
Mar 14 00:51:41 parsec-cloud-prod app/web.1 Traceback (most recent call last):
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/parsec/backend/cli/run.py", line 623, in _serve_client
Mar 14 00:51:41 parsec-cloud-prod app/web.1     await backend.handle_client(stream)
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/parsec/backend/app.py", line 194, in handle_client
Mar 14 00:51:41 parsec-cloud-prod app/web.1     await self._handle_client_http(stream, conn, event)
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/parsec/backend/app.py", line 276, in _handle_client_http
Mar 14 00:51:41 parsec-cloud-prod app/web.1     await self._send_http_reply(
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/parsec/backend/app.py", line 230, in _send_http_reply
Mar 14 00:51:41 parsec-cloud-prod app/web.1     await stream.send_all(conn.send(h11.Data(data=data)))
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/h11/_connection.py", line 468, in send
Mar 14 00:51:41 parsec-cloud-prod app/web.1     data_list = self.send_with_data_passthrough(event)
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/h11/_connection.py", line 501, in send_with_data_passthrough
Mar 14 00:51:41 parsec-cloud-prod app/web.1     writer(event, data_list.append)
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/h11/_writers.py", line 58, in __call__
Mar 14 00:51:41 parsec-cloud-prod app/web.1     self.send_data(event.data, write)
Mar 14 00:51:41 parsec-cloud-prod app/web.1   File "/app/.heroku/python/lib/python3.8/site-packages/h11/_writers.py", line 78, in send_data
Mar 14 00:51:41 parsec-cloud-prod app/web.1     raise LocalProtocolError("Too much data for declared Content-Length")
Mar 14 00:51:41 parsec-cloud-prod app/web.1 h11._util.LocalProtocolError: Too much data for declared Content-Length
```

on sentry: https://sentry.io/organizations/scille/issues/3088888740/?project=5953612&query=server_name%3A%22parsec-cloud-test-web-1%22

Error should come from here https://github.com/Scille/parsec-cloud/blob/64d26788c733b38db12c480754e9e730b32dc475/parsec/backend/app.py#L214-L230

where content length is calculated from len(data), which is very similar to what is done in h11 documentation:
```
# from https://h11.readthedocs.io/en/latest/examples.html
async def send_simple_response(wrapper, status_code, content_type, body):
    wrapper.info("Sending", status_code, "response with", len(body), "bytes")
    headers = wrapper.basic_headers()
    headers.append(("Content-Type", content_type))
    headers.append(("Content-Length", str(len(body))))
    res = h11.Response(status_code=status_code, headers=headers)
    await wrapper.send(res)
    await wrapper.send(h11.Data(data=body))
    await wrapper.send(h11.EndOfMessage())
```

Error seems to come when a 404 is hit (given the 404 page is constant, is content-length is always 823octets, which is correct in the header reported by sentry, however h11 complains about too much data...)

**Comment by touilleMan** [comment]
HTTP server part is now using Quart & Hypercorn, this bug is most likely gone.
