### ISSUE TITLE
broken Drag an drop file in parsec workspace widget

### ISSUE THREAD

**Issue by AntoineDupre** [Scille/parsec-cloud#2090]
Drag and drop a file in a folder from parsec workspace widget is not working 

```
2022-03-17T14:54:08.778425Z [error    ] Uncatched error
Traceback (most recent call last):
  File "/snap/parsec/213/site-packages/parsec/core/gui/trio_jobs.py", line 76, in __call__
    result = await self._fn(*self._args, **self._kwargs)
  File "/snap/parsec/213/site-packages/parsec/core/gui/files_widget.py", line 127, in _do_move_files
    name_we, *_ = src.name.str.split(".", 1)
AttributeError: 'str' object has no attribute 'str'
```

**Comment by Max-7** [comment]
Done
