### ISSUE TITLE
TimeoutError: tests/core/gui/test_files.py::test_file_browsing_and_edit

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2369]
https://dev.azure.com/Scille/parsec/_build/results?buildId=11644&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=b18150ab-3a6d-5272-0b08-a0dc06a2acd4&l=140t
```
2022-05-27T17:00:08.9816589Z tests/core/gui/test_files.py::test_file_browsing_and_edit FAILED         [ 13%]
2022-05-27T17:00:08.9817450Z 
2022-05-27T17:00:08.9817898Z ================================== FAILURES ===================================
2022-05-27T17:00:08.9818406Z _________________________ test_file_browsing_and_edit _________________________
2022-05-27T17:00:08.9818708Z 
2022-05-27T17:00:08.9828231Z self = <tests.core.gui.conftest.AsyncQtBot object at 0x0000019D96C8C100>
2022-05-27T17:00:08.9829020Z callback = <function create_files_widget_testbed.<locals>.FilesWidgetTestbed.cd.<locals>._path_reached at 0x0000019D99F7ADC0>
2022-05-27T17:00:08.9829418Z 
2022-05-27T17:00:08.9830011Z     async def wait_until(self, callback, *, timeout=1000):
2022-05-27T17:00:08.9830509Z         """Implementation shamelessly adapted from:
2022-05-27T17:00:08.9831057Z         https://github.com/pytest-dev/pytest-qt/blob/16b989d700dfb91fe389999d8e2676437169ed44/src/pytestqt/qtbot.py#L459
2022-05-27T17:00:08.9831541Z         """
2022-05-27T17:00:08.9831869Z         __tracebackhide__ = True
2022-05-27T17:00:08.9832182Z     
2022-05-27T17:00:08.9832679Z         start = trio.current_time()
2022-05-27T17:00:08.9833007Z     
2022-05-27T17:00:08.9833319Z         def timed_out():
2022-05-27T17:00:08.9833685Z             elapsed = trio.current_time() - start
2022-05-27T17:00:08.9834071Z             elapsed_ms = elapsed * 1000
2022-05-27T17:00:08.9834441Z             return elapsed_ms > timeout
2022-05-27T17:00:08.9834763Z     
2022-05-27T17:00:08.9835128Z         timeout_msg = f"wait_until timed out in {timeout} milliseconds"
2022-05-27T17:00:08.9835503Z     
2022-05-27T17:00:08.9835806Z         while True:
2022-05-27T17:00:08.9836119Z             try:
2022-05-27T17:00:08.9836438Z >               result = callback()
2022-05-27T17:00:08.9836662Z 
2022-05-27T17:00:08.9836995Z tests\core\gui\conftest.py:95: 
2022-05-27T17:00:08.9837422Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2022-05-27T17:00:08.9838339Z 
2022-05-27T17:00:08.9838664Z     def _path_reached():
2022-05-27T17:00:08.9839127Z         fs_path = FsPath("/" + "/".join([part.str for part in current_path_parts]))
2022-05-27T17:00:08.9839592Z         assert f_w.current_directory == fs_path
2022-05-27T17:00:08.9840130Z >       assert c_w.navigation_bar_widget.get_current_path() == fs_path
2022-05-27T17:00:08.9840636Z E       AssertionError: assert FsPath('/dir3/dir33/dir31') == FsPath('/dir3/dir33')
2022-05-27T17:00:08.9841081Z E         +FsPath('/dir3/dir33/dir31')
2022-05-27T17:00:08.9841453Z E         -FsPath('/dir3/dir33')
2022-05-27T17:00:08.9841679Z 
2022-05-27T17:00:08.9842041Z tests\core\gui\test_files.py:63: AssertionError
2022-05-27T17:00:08.9842311Z 
2022-05-27T17:00:08.9842677Z The above exception was the direct cause of the following exception:
2022-05-27T17:00:08.9842966Z 
2022-05-27T17:00:08.9843320Z value = <trio.Nursery object at 0x0000019D94FD99D0>
2022-05-27T17:00:08.9843595Z 
2022-05-27T17:00:08.9843909Z     async def yield_(value=None):
2022-05-27T17:00:08.9844279Z >       return await _yield_(value)
2022-05-27T17:00:08.9844515Z 
2022-05-27T17:00:08.9844972Z C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\async_generator\_impl.py:106: 
2022-05-27T17:00:08.9845518Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2022-05-27T17:00:08.9846081Z C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\async_generator\_impl.py:99: in _yield_
2022-05-27T17:00:08.9846593Z     return (yield _wrap(value))
2022-05-27T17:00:08.9847016Z tests\core\gui\test_files.py:362: in test_file_browsing_and_edit
2022-05-27T17:00:08.9847441Z     await tb.cd("../..")
2022-05-27T17:00:08.9847841Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2022-05-27T17:00:08.9848101Z 
2022-05-27T17:00:08.9848571Z self = <tests.core.gui.test_files.create_files_widget_testbed.<locals>.FilesWidgetTestbed object at 0x0000019D96D63280>
2022-05-27T17:00:08.9849056Z path = '../..'
2022-05-27T17:00:08.9849255Z 
2022-05-27T17:00:08.9849583Z     async def cd(self, path):
2022-05-27T17:00:08.9850075Z         current_path_parts = [p for p in c_w.navigation_bar_widget.paths]
2022-05-27T17:00:08.9850486Z         if path.startswith("/"):
2022-05-27T17:00:08.9850882Z             raise ValueError("Absolute path not supported")
2022-05-27T17:00:08.9851292Z         for name in path.split("/"):
2022-05-27T17:00:08.9851655Z             if name == "." or name == "":
2022-05-27T17:00:08.9851986Z                 continue
2022-05-27T17:00:08.9852315Z             elif name == "..":
2022-05-27T17:00:08.9852676Z                 if not current_path_parts:
2022-05-27T17:00:08.9853120Z                     raise ValueError("Root folder already reached, cannot go up anymore !")
2022-05-27T17:00:08.9853641Z                 f_w.table_files.item_activated.emit(FileType.ParentFolder, "Parent folder")
2022-05-27T17:00:08.9854083Z                 current_path_parts.pop()
2022-05-27T17:00:08.9854423Z             else:
2022-05-27T17:00:08.9854826Z                 f_w.table_files.item_activated.emit(FileType.Folder, name)
2022-05-27T17:00:08.9855361Z                 current_path_parts.append(EntryName(name))
2022-05-27T17:00:08.9855708Z     
2022-05-27T17:00:08.9856027Z             def _path_reached():
2022-05-27T17:00:08.9856454Z                 fs_path = FsPath("/" + "/".join([part.str for part in current_path_parts]))
2022-05-27T17:00:08.9856918Z                 assert f_w.current_directory == fs_path
2022-05-27T17:00:08.9857371Z                 assert c_w.navigation_bar_widget.get_current_path() == fs_path
2022-05-27T17:00:08.9857753Z     
2022-05-27T17:00:08.9858465Z >           await aqtbot.wait_until(_path_reached)
2022-05-27T17:00:08.9859048Z E           pytestqt.exceptions.TimeoutError: wait_until timed out in 1000 milliseconds
2022-05-27T17:00:08.9859350Z 
2022-05-27T17:00:08.9859718Z tests\core\gui\test_files.py:65: TimeoutError
2022-05-27T17:00:08.9860536Z ---------------------------- Captured Qt messages -----------------------------
2022-05-27T17:00:08.9861106Z QtWarningMsg: QLayout: Attempting to add QLayout "" to NavigationBarWidget "navigation_bar_widget", which already has a layout
2022-05-27T17:00:08.9861701Z QtWarningMsg: QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
2022-05-27T17:00:08.9862210Z ------------------------------ Captured log call ------------------------------
2022-05-27T17:00:08.9864816Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:05 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.GUI_CONFIG_CHANGED: 'gui.config.changed'> gui_last_device=bob@dev1
2022-05-27T17:00:08.9866412Z DEBUG    parsec.core.backend_connection.proxy:proxy.py:59 2022-05-27 17:00:05 [debug    ] Retreiving .PAC proxy config url from system [parsec.core.backend_connection.proxy] 
2022-05-27T17:00:08.9867466Z DEBUG    parsec.core.backend_connection.proxy:proxy.py:165 2022-05-27 17:00:05 [debug    ] No proxy configuration found for target URL, using direct access [parsec.core.backend_connection.proxy] target_url=http://bob_dev1.example.com:9999
2022-05-27T17:00:08.9868586Z DEBUG    parsec.core.backend_connection.transport:transport.py:88 2022-05-27 17:00:05 [debug    ] Using direct (no proxy) connection [parsec.core.backend_connection.transport] hostname=bob_dev1.example.com port=9999
2022-05-27T17:00:08.9869574Z DEBUG    parsec.core.backend_connection.transport:transport.py:93 2022-05-27 17:00:05 [debug    ] Impossible to connect to backend [parsec.core.backend_connection.transport] hostname=bob_dev1.example.com port=9999
2022-05-27T17:00:08.9870339Z Traceback (most recent call last):
2022-05-27T17:00:08.9870900Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\parsec\core\backend_connection\transport.py", line 90, in _connect
2022-05-27T17:00:08.9871462Z     stream = await trio.open_tcp_stream(hostname, port)
2022-05-27T17:00:08.9871935Z   File "D:\a\1\s\tests\open_tcp_stream_mock_wrapper.py", line 62, in __call__
2022-05-27T17:00:08.9872414Z     raise ConnectionRefusedError(111, "Connection refused")
2022-05-27T17:00:08.9872867Z ConnectionRefusedError: [Errno 111] Connection refused
2022-05-27T17:00:08.9873736Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:05 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.BACKEND_CONNECTION_CHANGED: 'backend.connection.changed'> status=<BackendConnStatus.LOST: 2> status_exc=BackendNotAvailable(ConnectionRefusedError(111, 'Connection refused'))
2022-05-27T17:00:08.9874808Z INFO     parsec.core.backend_connection.authenticated:authenticated.py:292 2022-05-27 17:00:05 [info     ] Backend offline                [parsec.core.backend_connection.authenticated] cooldown_time=0
2022-05-27T17:00:08.9875690Z DEBUG    parsec.core.backend_connection.proxy:proxy.py:59 2022-05-27 17:00:05 [debug    ] Retreiving .PAC proxy config url from system [parsec.core.backend_connection.proxy] 
2022-05-27T17:00:08.9876656Z DEBUG    parsec.core.backend_connection.proxy:proxy.py:165 2022-05-27 17:00:05 [debug    ] No proxy configuration found for target URL, using direct access [parsec.core.backend_connection.proxy] target_url=http://bob_dev1.example.com:9999
2022-05-27T17:00:08.9877774Z DEBUG    parsec.core.backend_connection.transport:transport.py:88 2022-05-27 17:00:05 [debug    ] Using direct (no proxy) connection [parsec.core.backend_connection.transport] hostname=bob_dev1.example.com port=9999
2022-05-27T17:00:08.9878744Z DEBUG    parsec.core.backend_connection.transport:transport.py:93 2022-05-27 17:00:05 [debug    ] Impossible to connect to backend [parsec.core.backend_connection.transport] hostname=bob_dev1.example.com port=9999
2022-05-27T17:00:08.9879952Z Traceback (most recent call last):
2022-05-27T17:00:08.9880639Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\parsec\core\backend_connection\transport.py", line 90, in _connect
2022-05-27T17:00:08.9881292Z     stream = await trio.open_tcp_stream(hostname, port)
2022-05-27T17:00:08.9881760Z   File "D:\a\1\s\tests\open_tcp_stream_mock_wrapper.py", line 62, in __call__
2022-05-27T17:00:08.9882232Z     raise ConnectionRefusedError(111, "Connection refused")
2022-05-27T17:00:08.9882674Z ConnectionRefusedError: [Errno 111] Connection refused
2022-05-27T17:00:08.9883362Z INFO     parsec.core.backend_connection.authenticated:authenticated.py:292 2022-05-27 17:00:05 [info     ] Backend offline                [parsec.core.backend_connection.authenticated] cooldown_time=1
2022-05-27T17:00:08.9884311Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:05 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 8bf5c61f1f9a4328b66f60cd8ea63647>
2022-05-27T17:00:08.9885804Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:05 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_WORKSPACE_CREATED: 'fs.workspace.created'> new_entry=WorkspaceEntry(name=<EntryName wksp1>, id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>, key=SecretKey(<redacted>), encryption_revision=1, encrypted_on=DateTime(2022, 5, 27, 17, 0, 5, 929329, tzinfo=Timezone('UTC')), role_cached_on=DateTime(2022, 5, 27, 17, 0, 5, 929329, tzinfo=Timezone('UTC')), role=<RealmRole.OWNER: 'OWNER'>)
2022-05-27T17:00:08.9887292Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:05 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.MOUNTPOINT_STARTING: 'mountpoint.starting'> mountpoint=PureWindowsPath('P:/') workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9888414Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.MOUNTPOINT_STARTED: 'mountpoint.started'> mountpoint=PureWindowsPath('P:/') workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9889686Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9890922Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 60b68e6fdc524c18bd7b882ee8111911> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9892066Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9893204Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5b0bb9db38d45cab8c4b6a0b71266a2> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9894428Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9895562Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID bac3070527ec4e9a95fe9a3d001340b9> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9896684Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9898325Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID f75cacf029824acab48d3e0ef3c96c89> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9899449Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9900665Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID dce8cc46d3244239a9eae4714bba7fdd> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9901790Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9904340Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 7c3a3abeed3e4117a29727692ca6c99f> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9905518Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 7c3a3abeed3e4117a29727692ca6c99f> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9906651Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 1aef2344bb3c4c6799528522568338d4> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9907774Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 1aef2344bb3c4c6799528522568338d4> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9908905Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID a1eafc85262443788414a2f780bf912e> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9910141Z DEBUG    parsec.core.backend_connection.proxy:proxy.py:59 2022-05-27 17:00:06 [debug    ] Retreiving .PAC proxy config url from system [parsec.core.backend_connection.proxy] 
2022-05-27T17:00:08.9926620Z DEBUG    parsec.core.backend_connection.proxy:proxy.py:165 2022-05-27 17:00:06 [debug    ] No proxy configuration found for target URL, using direct access [parsec.core.backend_connection.proxy] target_url=http://bob_dev1.example.com:9999
2022-05-27T17:00:08.9927910Z DEBUG    parsec.core.backend_connection.transport:transport.py:88 2022-05-27 17:00:06 [debug    ] Using direct (no proxy) connection [parsec.core.backend_connection.transport] hostname=bob_dev1.example.com port=9999
2022-05-27T17:00:08.9928921Z DEBUG    parsec.core.backend_connection.transport:transport.py:93 2022-05-27 17:00:06 [debug    ] Impossible to connect to backend [parsec.core.backend_connection.transport] hostname=bob_dev1.example.com port=9999
2022-05-27T17:00:08.9929605Z Traceback (most recent call last):
2022-05-27T17:00:08.9930315Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\parsec\core\backend_connection\transport.py", line 90, in _connect
2022-05-27T17:00:08.9931029Z     stream = await trio.open_tcp_stream(hostname, port)
2022-05-27T17:00:08.9931514Z   File "D:\a\1\s\tests\open_tcp_stream_mock_wrapper.py", line 62, in __call__
2022-05-27T17:00:08.9931994Z     raise ConnectionRefusedError(111, "Connection refused")
2022-05-27T17:00:08.9932431Z ConnectionRefusedError: [Errno 111] Connection refused
2022-05-27T17:00:08.9933116Z INFO     parsec.core.backend_connection.authenticated:authenticated.py:292 2022-05-27 17:00:06 [info     ] Backend offline                [parsec.core.backend_connection.authenticated] cooldown_time=2
2022-05-27T17:00:08.9934156Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9935320Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9936474Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:06 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9937604Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9940021Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9942260Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9943492Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID d5918cb843ca4f44bd40821be1a6fa10> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9945109Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID 7c3a3abeed3e4117a29727692ca6c99f> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9946924Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID c55e8de61e9f44b3a6330a7a4401196d> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9948054Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID c55e8de61e9f44b3a6330a7a4401196d> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9949191Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID c24f6375561649199cbeb091382227d3> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9950517Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID c24f6375561649199cbeb091382227d3> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9951669Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:07 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.FS_ENTRY_UPDATED: 'fs.entry.updated'> id=<EntryID db6cbf36c9f74e4c97302e5cf13d6c99> workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9952838Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:08 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.MOUNTPOINT_STOPPING: 'mountpoint.stopping'> mountpoint=PureWindowsPath('P:/') workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9953976Z DEBUG    parsec.event_bus:event_bus.py:86 2022-05-27 17:00:08 [debug    ] Send event                     [parsec.event_bus] event_type=<CoreEvent.MOUNTPOINT_STOPPED: 'mountpoint.stopped'> mountpoint=PureWindowsPath('P:/') workspace_id=<EntryID d5918cb843ca4f44bd40821be1a6fa10>
2022-05-27T17:00:08.9954790Z -------------- generated xml file: D:\a\1\s\test-results-gui.xml --------------
2022-05-27T17:00:08.9955291Z ============================ slowest 10 durations =============================
2022-05-27T17:00:08.9955813Z 19.53s call     tests/test_cli.py::test_gui_with_diagnose_option[Standard environement]
2022-05-27T17:00:08.9956343Z 6.37s call     tests/core/gui/test_dialog.py::test_file_dialog_in_process
2022-05-27T17:00:08.9956857Z 3.29s call     tests/core/gui/test_files.py::test_file_browsing_and_edit
2022-05-27T17:00:08.9957387Z 3.15s call     tests/test_cli.py::test_gui_with_diagnose_option[Wrong winfsp binary path]
2022-05-27T17:00:08.9957938Z 3.04s call     tests/test_cli.py::test_gui_with_diagnose_option[Wrong winfsp library path]
2022-05-27T17:00:08.9958494Z 2.54s call     tests/core/gui/test_enrollment.py::test_full_enrollment[mock_parsec_ext]
2022-05-27T17:00:08.9959081Z 2.25s call     tests/core/gui/test_authentication_change.py::test_change_password_invalid_old_password
2022-05-27T17:00:08.9959629Z 1.43s call     tests/core/gui/test_file_history.py::test_file_history
2022-05-27T17:00:08.9960364Z 1.18s call     tests/core/gui/test_create_organization.py::test_create_organization
2022-05-27T17:00:08.9960961Z 1.12s call     tests/core/gui/test_create_organization.py::test_create_organization_custom_backend
2022-05-27T17:00:08.9961503Z =========================== short test summary info ===========================
```

**Comment by touilleMan** [comment]
not seen for a long time, closing
