### ISSUE TITLE
[🐛 | Bug]: Fuse could not be loaded. Please check your installation

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2501]
### Version

2.9.2

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

After performing the step to add a new device,
The newly added device displayed the bellow error message, just after completing the process.

PS: I can't log in, When I enter the password I've the error display but still in the login page

## Error Message

![image](https://user-images.githubusercontent.com/30697622/175266675-cf28c5c6-2402-401e-80e6-845799296d42.png)

## Trace from GUI

```
MountpointFuseNotAvailable

Traceback (most recent call last):
  File "/snap/parsec/224/site-packages/parsec/core/mountpoint/manager.py", line 68, in get_mountpoint_runner
    import_function("fuse")
  File "<frozen importlib._bootstrap>", line 1109, in __import__
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/snap/parsec/224/site-packages/fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/parsec/224/site-packages/parsec/core/gui/trio_jobs.py", line 76, in __call__
    result = await self._fn(*self._args, **self._kwargs)
  File "/snap/parsec/224/site-packages/parsec/core/gui/instance_widget.py", line 46, in _do_run_core
    async with logged_core_factory(config=config, device=device, event_bus=None) as core:
  File "/snap/parsec/224/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/snap/parsec/224/site-packages/parsec/core/logged_core.py", line 405, in logged_core_factory
    async with mountpoint_manager_factory(
  File "/snap/parsec/224/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/snap/parsec/224/site-packages/parsec/core/mountpoint/manager.py", line 355, in mountpoint_manager_factory
    runner = get_mountpoint_runner()
  File "/snap/parsec/224/site-packages/parsec/core/mountpoint/manager.py", line 70, in get_mountpoint_runner
    raise MountpointFuseNotAvailable(exc) from exc
parsec.core.mountpoint.exceptions.MountpointFuseNotAvailable: Unable to find libfuse
```

## Snap fuse lib

```shell
$ ls /snap/parsec/current/lib/x86_64-linux-gnu/libfuse.so.2*
/snap/parsec/current/lib/x86_64-linux-gnu/libfuse.so.2
/snap/parsec/current/lib/x86_64-linux-gnu/libfuse.so.2.9.9
```

**Comment by vxgmichel** [comment]
Fixed here: https://github.com/Scille/parsec-cloud/pull/2498/commits/338f0712ec826dc4480b1c89468cf2cb72bf95be

**Comment by FirelightFlagboy** [comment]
Re-opening since the fix isn't working

**Comment by FirelightFlagboy** [comment]
here is the error details given by the application

```
MountpointFuseNotAvailable

Traceback (most recent call last):
  File "/snap/parsec/226/site-packages/parsec/core/mountpoint/manager.py", line 67, in get_mountpoint_runner
    import_function("fuse")
  File "<frozen importlib._bootstrap>", line 1109, in __import__
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/snap/parsec/226/site-packages/fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/parsec/226/site-packages/parsec/core/gui/trio_jobs.py", line 76, in __call__
    result = await self._fn(*self._args, **self._kwargs)
  File "/snap/parsec/226/site-packages/parsec/core/gui/instance_widget.py", line 46, in _do_run_core
    async with logged_core_factory(config=config, device=device, event_bus=None) as core:
  File "/snap/parsec/226/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/snap/parsec/226/site-packages/parsec/core/logged_core.py", line 405, in logged_core_factory
    async with mountpoint_manager_factory(
  File "/snap/parsec/226/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/snap/parsec/226/site-packages/parsec/core/mountpoint/manager.py", line 354, in mountpoint_manager_factory
    runner = get_mountpoint_runner()
  File "/snap/parsec/226/site-packages/parsec/core/mountpoint/manager.py", line 69, in get_mountpoint_runner
    raise MountpointFuseNotAvailable(exc) from exc
parsec.core.mountpoint.exceptions.MountpointFuseNotAvailable: Unable to find libfuse
```

**Comment by FirelightFlagboy** [comment]
One workaround could be setting `FUSE_LIBRARY_PATH`
