### ISSUE TITLE
[🐛 | Bug]: Email is invalid

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2502]
### Version

2.10.0-rc1

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

Will joining a new organization a got an invalid email error, beside that the email is valid `foo.bar@gmail.com`

## Trace

![image](https://user-images.githubusercontent.com/30697622/175269957-4780b027-44ba-4f36-ad16-b10cdac19e2f.png)

```
ValueError

Traceback (most recent call last):
  File "/snap/parsec/225/site-packages/parsec/core/gui/claim_user_widget.py", line 471, in _on_claim_clicked
    human_handle = HumanHandle(email=self.line_edit_user_email.text(), label=user_name)
  File "/snap/parsec/225/site-packages/parsec/api/protocol/types.py", line 186, in __new__
    raise ValueError("Invalid email/label couple")
ValueError: Invalid email/label couple
````

**Comment by FirelightFlagboy** [comment]
The error was, I was using the following **full name**: `[Object] object`
