### ISSUE TITLE
[🐛 | Bug]: Error while importing a folder in the GUI

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#2696]
### Version

2.11.0rc2

### What platforms you were running our software when the bug happened ?

Windows

### What happened ?

Error while importing a whole folder in the GUI. Seems to happen for while that don't have an extension.

### Relevant output

```
ValueError

Traceback (most recent call last):
  File "parsec\core\gui\files_widget.py", line 758, in _do_import
  File "parsec\core\gui\files_widget.py", line 859, in _import_all
  File "parsec\core\gui\files_widget.py", line 891, in _import_one
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by AntoineDupre** [comment]
Same error, can not import a file without extension. It's seems to be only GUI related (the file can be imported from the mountpoint)
