### ISSUE TITLE
Unstable test `test_swift_get`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2705]
The test `test_swift_get` failed with the following error:

```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/base_events.py", line 1779, in call_exception_handler
    self.default_exception_handler(context)
  File "/home/runner/.cache/pypoetry/virtualenvs/parsec-cloud-dZ-E5qY_-py3.9/lib/python3.9/site-packages/trio_asyncio/_async.py", line 44, in default_exception_handler
    raise exception
ConnectionError: unexpected connection_lost() call
```

The test can be found here

https://github.com/Scille/parsec-cloud/blob/e77b13259a6023e7fbb359cfde5ea6bd8795a3ea/tests/backend/test_swift_blockstore.py#L13-L49

You can find the log here: <https://github.com/Scille/parsec-cloud/runs/7535800668?check_suite_focus=true#step:14:256>

**Comment by FirelightFlagboy** [comment]
Got another failure on another test `test_conduit_exchange_good`

https://github.com/Scille/parsec-cloud/runs/7686993043?check_suite_focus=true#step:14:162
