### ISSUE TITLE
[🐛 | Bug]: Snap crash with ubuntu 22.04

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#3067]
### Version

2.12.0

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

```
$ parsec.cli --version
Traceback (most recent call last):
  File "/snap/parsec/235/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/snap/parsec/235/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/miguel/projects/parsec-cloud/parsec/__init__.py", line 21, in <module>
    __import__("parsec.utils")
  File "/home/miguel/projects/parsec-cloud/parsec/utils.py", line 5, in <module>
    from parsec._parsec import DateTime
ImportError: /snap/parsec/235/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/miguel/projects/parsec-cloud/parsec/_parsec.abi3.so)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by touilleMan** [comment]
see also https://docs.python.org/3.11/using/cmdline.html?highlight=pythonpath#cmdoption-P

**Comment by FirelightFlagboy** [comment]
@touilleMan This issue is for the version 2.12 which is old can we close it ?

**Comment by touilleMan** [comment]
This is mainly an issue when doing dev, and it should be fixed in Parsec v3 given we won't ship python at all ^^
