### ISSUE TITLE
[GUI] sharing button not working

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#308]
```
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 114, in share_workspace
    d = WorkspaceSharingDialog(workspace_button.name, self.core, self.portal)
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspace_sharing_dialog.py", line 72, in __init__
    self.button_apply.clicked.connect(self.apply_changes)
AttributeError: 'WorkspaceSharingDialog' object has no attribute 'button_apply'
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 114, in share_workspace
    d = WorkspaceSharingDialog(workspace_button.name, self.core, self.portal)
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspace_sharing_dialog.py", line 72, in __init__
    self.button_apply.clicked.connect(self.apply_changes)
AttributeError: 'WorkspaceSharingDialog' object has no attribute 'button_apply'
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 114, in share_workspace
    d = WorkspaceSharingDialog(workspace_button.name, self.core, self.portal)
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspace_sharing_dialog.py", line 72, in __init__
    self.button_apply.clicked.connect(self.apply_changes)
AttributeError: 'WorkspaceSharingDialog' object has no attribute 'button_apply'
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 114, in share_workspace
    d = WorkspaceSharingDialog(workspace_button.name, self.core, self.portal)
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspace_sharing_dialog.py", line 72, in __init__
    self.button_apply.clicked.connect(self.apply_changes)
AttributeError: 'WorkspaceSharingDialog' object has no attribute 'button_apply'
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 114, in share_workspace
    d = WorkspaceSharingDialog(workspace_button.name, self.core, self.portal)
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspace_sharing_dialog.py", line 72, in __init__
    self.button_apply.clicked.connect(self.apply_changes)
AttributeError: 'WorkspaceSharingDialog' object has no attribute 'button_apply'
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 114, in share_workspace
    d = WorkspaceSharingDialog(workspace_button.name, self.core, self.portal)
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\workspace_sharing_dialog.py", line 72, in __init__
    self.button_apply.clicked.connect(self.apply_changes)
AttributeError: 'WorkspaceSharingDialog' object has no attribute 'button_apply'
```
parsec version: 0.10.3
platform: windows

**Comment by Max-7** [comment]
It feels like the forms were not properly generated. "button_apply" is present and it works correctly on my pc.
@touilleMan @frossigneux Was `python setup.py generate_pyqt` executed ?
