### ISSUE TITLE
[GUI] traceback while creating folder

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#309]
```
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\files_widget.py", line 366, in show_context_menu
    file_type = type_item.data(Qt.UserRole)
AttributeError: 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "c:\users\gbleu\source\repos\parsec-cloud\parsec\core\gui\files_widget.py", line 366, in show_context_menu
    file_type = type_item.data(Qt.UserRole)
AttributeError: 'NoneType' object has no attribute 'data'
```

parsec version: 0.10.3
platform: windows

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/ddb72e141fdfa7599e78ef0dff617e87486e361f
