### ISSUE TITLE
[🐛 | Bug]: Login fails on master

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#3212]
### Version

master

### What platforms you were running our software when the bug happened ?

Windows

### What happened ?

Login fails when trying to log to an existing organization.

### Relevant output

2022-10-06T06:56:03.699236Z [error    ] Unhandled error
Traceback (most recent call last):
  File "E:\projects\parsec-cloud\parsec\core\gui\trio_jobs.py", line 97, in __call__
    result = await self._fn(*self._args, **self._kwargs)
  File "E:\projects\parsec-cloud\parsec\core\gui\instance_widget.py", line 47, in _do_run_core
    async with logged_core_factory(config=config, device=device, event_bus=None) as core:
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "E:\projects\parsec-cloud\parsec\core\logged_core.py", line 412, in logged_core_factory
    async with UserFS.run(
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "E:\projects\parsec-cloud\parsec\core\fs\userfs\userfs.py", line 331, in run
    await self._load_workspace(workspace_entry.id)
  File "E:\projects\parsec-cloud\parsec\core\fs\userfs\userfs.py", line 438, in _load_workspace
    workspace = await self._instantiate_workspace(workspace_id)
  File "E:\projects\parsec-cloud\parsec\core\fs\userfs\userfs.py", line 408, in _instantiate_workspace
    local_storage = await self._workspace_storage_nursery.start(workspace_storage_task)
  File "E:\projects\parsec-cloud\parsec\service_nursery.py", line 183, in start
    return await type(nursery).start(nursery, wrap_child, name=name or async_fn)
  File "E:\projects\parsec-cloud\venv\lib\site-packages\trio\_core\_run.py", line 1042, in start
    task._eventual_parent_nursery = self
  File "E:\projects\parsec-cloud\venv\lib\site-packages\trio\_core\_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "E:\projects\parsec-cloud\parsec\service_nursery.py", line 181, in wrap_child
    await async_fn(*args, task_status=task_status)
  File "E:\projects\parsec-cloud\parsec\core\fs\userfs\userfs.py", line 399, in workspace_storage_task
    async with WorkspaceStorage.run(
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "E:\projects\parsec-cloud\parsec\core\fs\storage\workspace_storage.py", line 325, in run
    await instance._load_prevent_sync_pattern()
  File "E:\projects\parsec-cloud\parsec\core\fs\storage\workspace_storage.py", line 420, in _load_prevent_sync_pattern
    ) = await self.manifest_storage.get_prevent_sync_pattern()
  File "E:\projects\parsec-cloud\parsec\core\fs\storage\manifest_storage.py", line 138, in get_prevent_sync_pattern
    return (Regex.from_regex_str(pattern), bool(fully_applied))
parsec.core.gui.trio_jobs.JobResultError: ('crashed', {'exc': ValueError('Invalid regex `(?s:.*\\.tmp)\\Z|(?s:.*\\.temp)\\Z|(?s:.*\\.swp)\\Z|(?s:.*\\~)\\Z|(?s:\\.fuse_hidden.*)\\Z|(?s:\\.directory)\\Z|(?s:\\.Trash\\-.*)\\Z|(?s:\\.nfs.*)\\Z|(?s:\\.goutputstream\\-.*)\\Z|(?s:\\.DS_Store)\\Z|(?s:\\.AppleDouble)\\Z|(?s:\\.LSOverride)\\Z|(?s:\\._.*)\\Z|(?s:\\.DocumentRevisions\\-V100)\\Z|(?s:\\.Spotlight\\-V100)\\Z|(?s:\\.TemporaryItems)\\Z|(?s:\\.Trashes)\\Z|(?s:\\.VolumeIcon\\.icns)\\Z|(?s:\\.com\\.apple\\.timemachine\\.donotpresent)\\Z|(?s:\\.AppleDB)\\Z|(?s:\\.AppleDesktop)\\Z|(?s:Network\\ Trash\\ Folder)\\Z|(?s:Temporary\\ Items)\\Z|(?s:\\.apdisk)\\Z|(?s:\\.fseventsd)\\Z|(?s:(?=(?P<g0>.*?\\.))(?P=g0)(?=(?P<g1>.*?\\.sb\\-))(?P=g1)(?=(?P<g2>.*?\\-))(?P=g2).*)\\Z|(?s:Thumbs\\.db)\\Z|(?s:Thumbs\\.db:encryptable)\\Z|(?s:ehthumbs\\.db)\\Z|(?s:ehthumbs_vista\\.db)\\Z|(?s:.*\\.stackdump)\\Z|(?s:[Dd]esktop\\.ini)\\Z|(?s:\\$RECYCLE\\.BIN)\\Z|(?s:.*\\.lnk)\\Z|(?s:\\.\\~.*)\\Z|(?s:\\~\\$.*)\\Z`'), 'info': "Unexpected error: ValueError('Invalid regex `(?s:.*\\\\.tmp)\\\\Z|(?s:.*\\\\.temp)\\\\Z|(?s:.*\\\\.swp)\\\\Z|(?s:.*\\\\~)\\\\Z|(?s:\\\\.fuse_hidden.*)\\\\Z|(?s:\\\\.directory)\\\\Z|(?s:\\\\.Trash\\\\-.*)\\\\Z|(?s:\\\\.nfs.*)\\\\Z|(?s:\\\\.goutputstream\\\\-.*)\\\\Z|(?s:\\\\.DS_Store)\\\\Z|(?s:\\\\.AppleDouble)\\\\Z|(?s:\\\\.LSOverride)\\\\Z|(?s:\\\\._.*)\\\\Z|(?s:\\\\.DocumentRevisions\\\\-V100)\\\\Z|(?s:\\\\.Spotlight\\\\-V100)\\\\Z|(?s:\\\\.TemporaryItems)\\\\Z|(?s:\\\\.Trashes)\\\\Z|(?s:\\\\.VolumeIcon\\\\.icns)\\\\Z|(?s:\\\\.com\\\\.apple\\\\.timemachine\\\\.donotpresent)\\\\Z|(?s:\\\\.AppleDB)\\\\Z|(?s:\\\\.AppleDesktop)\\\\Z|(?s:Network\\\\ Trash\\\\ Folder)\\\\Z|(?s:Temporary\\\\ Items)\\\\Z|(?s:\\\\.apdisk)\\\\Z|(?s:\\\\.fseventsd)\\\\Z|(?s:(?=(?P<g0>.*?\\\\.))(?P=g0)(?=(?P<g1>.*?\\\\.sb\\\\-))(?P=g1)(?=(?P<g2>.*?\\\\-))(?P=g2).*)\\\\Z|(?s:Thumbs\\\\.db)\\\\Z|(?s:Thumbs\\\\.db:encryptable)\\\\Z|(?s:ehthumbs\\\\.db)\\\\Z|(?s:ehthumbs_vista\\\\.db)\\\\Z|(?s:.*\\\\.stackdump)\\\\Z|(?s:[Dd]esktop\\\\.ini)\\\\Z|(?s:\\\\$RECYCLE\\\\.BIN)\\\\Z|(?s:.*\\\\.lnk)\\\\Z|(?s:\\\\.\\\\~.*)\\\\Z|(?s:\\\\~\\\\$.*)\\\\Z`')"})

**Comment by Volham22** [comment]
The non escaped regex is 
```
(?s:.*\.tmp)\Z|(?s:.*\.temp)\Z|(?s:.*\.swp)\Z|(?s:.*\~)\Z|(?s:\.fuse_hidden.*)\Z|(?s:\.directory)\Z|(?s:\.Trash\-.*)\Z|(?s:\.nfs.*)\Z|(?s:\.goutputstream\-.*)\Z|(?s:\.DS_Store)\Z|(?s:\.AppleDouble)\Z|(?s:\.LSOverride)\Z|(?s:\._.*)\Z|(?s:\.DocumentRevisions\-V100)\Z|(?s:\.Spotlight\-V100)\Z|(?s:\.TemporaryItems)\Z|(?s:\.Trashes)\Z|(?s:\.VolumeIcon\.icns)\Z|(?s:\.com\.apple\.timemachine\.donotpresent)\Z|(?s:\.AppleDB)\Z|(?s:\.AppleDesktop)\Z|(?s:Network\ Trash\ Folder)\Z|(?s:Temporary\ Items)\Z|(?s:\.apdisk)\Z|(?s:\.fseventsd)\Z|(?s:(?=(?P<g0>.*?\.))(?P=g0)(?=(?P<g1>.*?\.sb\-))(?P=g1)(?=(?P<g2>.*?\-))(?P=g2).*)\Z|(?s:Thumbs\.db)\Z|(?s:Thumbs\.db:encryptable)\Z|(?s:ehthumbs\.db)\Z|(?s:ehthumbs_vista\.db)\Z|(?s:.*\.stackdump)\Z|(?s:[Dd]esktop\.ini)\Z|(?s:\$RECYCLE\.BIN)\Z|(?s:.*\.lnk)\Z|(?s:\.\~.*)\Z|(?s:\~\$.*)\Z
```
