### ISSUE TITLE
Fix invite without HumanHandle

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#3507]
```
AttributeError

Traceback (most recent call last):
  File "/home/vinmic/repos/parsec-cloud/parsec/core/gui/claim_user_widget.py", line 79, in run
    initial_ctx = cast(UserClaimInitialCtx, await claimer_retrieve_info(cmds))
  File "/home/vinmic/repos/parsec-cloud/parsec/core/invite/claimer.py", line 182, in claimer_retrieve_info
    greeter_human_handle=rep_ok.greeter_human_handle,
AttributeError: rep in not ok
```

**Comment by vxgmichel** [comment]
A possible fix:
```diff
diff --git a/src/protocol/invite.rs b/src/protocol/invite.rs
index cf8affe1d..739fdee7f 100644
--- a/src/protocol/invite.rs
+++ b/src/protocol/invite.rs
@@ -707,17 +707,25 @@ impl InviteInfoRepOk {
     }
 
     #[getter]
-    fn greeter_human_handle(_self: PyRef<'_, Self>) -> PyResult<HumanHandle> {
+    fn greeter_human_handle(_self: PyRef<'_, Self>) -> PyResult<Option<HumanHandle>> {
         match &_self.as_ref().0 {
             invite_info::Rep::Ok(invite_info::UserOrDevice::Device {
                 greeter_human_handle: Some(handle),
                 ..
-            }) => Ok(HumanHandle(handle.clone())),
+            }) => Ok(Some(HumanHandle(handle.clone()))),
             invite_info::Rep::Ok(invite_info::UserOrDevice::User {
                 greeter_human_handle: Some(handle),
                 ..
-            }) => Ok(HumanHandle(handle.clone())),
-            _ => Err(PyAttributeError::new_err("rep in not ok")),
+            }) => Ok(Some(HumanHandle(handle.clone()))),
+            invite_info::Rep::Ok(invite_info::UserOrDevice::Device {
+                greeter_human_handle: None,
+                ..
+            }) => Ok(None),
+            invite_info::Rep::Ok(invite_info::UserOrDevice::User {
+                greeter_human_handle: None,
+                ..
+            }) => Ok(None),
+            _ => Err(PyAttributeError::new_err("reply is not ok")),
         }
     }
 }
```

**Comment by vxgmichel** [comment]
Oops I did not see #3509
