### ISSUE TITLE
[GUI] Concurrency error when workspace widget try to a fs.stat during teardown

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#377]
see https://ci.appveyor.com/project/touilleMan/parsec-cloud/builds/23622280#L1794
```
============================= test session starts =============================
platform win32 -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.9.0 -- c:\python36-x64\python.exe
cachedir: .pytest_cache
PyQt5 5.11.2 -- Qt runtime 5.11.1 -- Qt compiled 5.11.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\projects\\parsec-cloud\\empty\\.hypothesis\\examples')
rootdir: C:\projects\parsec-cloud, inifile: setup.cfg
plugins: xdist-1.28.0, trio-0.5.2, qt-3.2.2, forked-1.0.2, cov-2.6.1, hypothesis-4.5.5
collecting ... collected 10 items
..\tests\gui\test_bootstrap_organization.py::test_bootstrap_organization PASSED [ 10%]
..\tests\gui\test_bootstrap_organization.py::test_bootstrap_organization_backend_offline PASSED [ 20%]
..\tests\gui\test_bootstrap_organization.py::test_bootstrap_organization_unknown_error PASSED [ 30%]
..\tests\gui\test_claim_device.py::test_claim_device PASSED              [ 40%]
..\tests\gui\test_claim_device.py::test_claim_device_offline PASSED      [ 50%]
..\tests\gui\test_claim_device.py::test_claim_device_unknown_error PASSED [ 60%]
..\tests\gui\test_claim_user.py::test_claim_user FAILED                  [ 70%]
================================== FAILURES ===================================
_______________________________ test_claim_user _______________________________
CALL ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "C:\projects\parsec-cloud\parsec\core\gui\main_window.py", line 138, in on_run_core_ready
    self.central_widget.set_core_attributes(core=core, portal=core_jobs_ctx)
  File "C:\projects\parsec-cloud\parsec\core\gui\central_widget.py", line 77, in set_core_attributes
    self.mount_widget.set_core_attributes(core, portal)
  File "C:\projects\parsec-cloud\parsec\core\gui\mount_widget.py", line 35, in set_core_attributes
    self.workspaces_widget.reset()
  File "C:\projects\parsec-cloud\parsec\core\gui\workspaces_widget.py", line 154, in reset
    result = self.portal.run(self.core.fs.stat, "/")
  File "C:\projects\parsec-cloud\parsec\core\gui\trio_thread.py", line 134, in run
    return self._portal.run(afn, *args)
  File "c:\python36-x64\lib\site-packages\trio\_threads.py", line 105, in run
    return self._do_it(self._run_cb, afn, *args)
  File "c:\python36-x64\lib\site-packages\trio\_threads.py", line 85, in _do_it
    self._trio_token.run_sync_soon(cb, q, fn, args)
  File "c:\python36-x64\lib\site-packages\trio\_core\_entry_queue.py", line 195, in run_sync_soon
    sync_fn, *args, idempotent=idempotent
  File "c:\python36-x64\lib\site-packages\trio\_core\_entry_queue.py", line 113, in run_sync_soon
    raise _core.RunFinishedError("run() has exited")
trio.RunFinishedError: run() has exited
________________________________________________________________________________
---------------------------- Captured std
```

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/2de6bd7372cd89c3a81405f6b2fbff0b6dfd23c0
