### ISSUE TITLE
[🐛 | Bug]: Mysterious fail from `test_block_storage`

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#4097]
### Version

2.15.0

### What platforms you were running our software when the bug happened ?

Windows

### What happened ?

Test failed: https://github.com/Scille/parsec-cloud/actions/runs/4282683866/jobs/7457264216

### Relevant output
```Shell
failures:

---- storage::chunk_storage::tests::test_block_storage stdout ----
thread 'storage::chunk_storage::tests::test_block_storage' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseClosed("Database is closed")', oxidation\libparsec\crates\core_fs\src\storage\chunk_storage.rs:[707](https://github.com/Scille/parsec-cloud/actions/runs/4282683866/jobs/7457264216#step:8:708):77
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\panicking.rs:65
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\result.rs:1791
   3: core::result::Result<T,E>::unwrap
   4: libparsec_core_fs::storage::chunk_storage::tests::test_chunk_interface::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: libparsec_core_fs::storage::chunk_storage::tests::test_block_interface::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: libparsec_core_fs::storage::chunk_storage::tests::test_block_storage::{{closure}}::test_block_storage::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: libparsec_core_fs::storage::chunk_storage::tests::test_block_storage::{{closure}}
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
  15: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
  16: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  18: tokio::macros::scoped_tls::ScopedKey<T>::set
  19: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  22: tokio::runtime::runtime::Runtime::block_on
  23: libparsec_core_fs::storage::chunk_storage::tests::test_block_storage::{{closure}}
  24: libparsec_core_fs::storage::chunk_storage::tests::test_block_storage::{{closure}}
  25: core::ops::function::FnOnce::call_once
  26: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\ops\function.rs:251
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    storage::chunk_storage::tests::test_block_storage

test result: FAILED. 24 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.87s

error: test failed, to rerun pass `-p libparsec_core_fs --lib`
Error: Process completed with exit code 101.
```

**Comment by FirelightFlagboy** [comment]
@TimeEngineer Could you add a title ?

**Comment by FirelightFlagboy** [comment]
Require #3930

**Comment by FirelightFlagboy** [comment]
This bug hasn't been reproduced since, I'm closing it for now.
But feel free to reopen it if needed
