### ISSUE TITLE
Error when running the `rename` and `move` windows commands 

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#411]
Taken from a windows test session with @frossigneux on #390:

```
C:\Users\Rossigneux\parsec_mnt\alice-alice_workspace>rename C D
Le fichier spécifié est introuvable.
C:\Users\Rossigneux\parsec_mnt\alice-alice_workspace>move D A
Le fichier spécifié est introuvable.
```

The winfsp mountpoint appears to work as expected when using file explorer or the python `os.rename` function:

```python
>>> os.rename("baz.txt", "E\\foo.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [WinError 17] Impossible de déplacer le fichier vers un lecteur de disque différent: 'baz.txt' -> 'E\\foo.txt'
>>> os.rename("baz.txt", "C:\\Users\\Rossigneux\\parsec_mnt\\alice-alice_workspace\\E\\foo.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [WinError 17] Impossible de déplacer le fichier vers un lecteur de disque différent: 'baz.txt' -> 'C:\\Users\\Rossigneux\\parsec_mnt\\alice-alice_workspace\\E\\foo.txt'
>>>
```

**Comment by vxgmichel** [comment]
As of today this is still hapening.

**Comment by vxgmichel** [comment]
Not happening anymore since #924
