### ISSUE TITLE
Error : Vite build doesn’t work on macOS

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#4407]
```
fabiensevestre@Fabiens-Air client % npm exec -- vite build 
PLATFORM environ variable not set, defaulting to `web`
vite v4.2.0 building for production...
✓ 315 modules transformed.
rendering chunks (20)...[vite-plugin-top-level-await] Fallback bindings does not support this interface yet.
✓ built in 4.02s
error during build:
Error: Fallback bindings does not support this interface yet.
    at Compiler.<anonymous> (/Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/@swc/core/index.js:119:23)
    at Generator.next (<anonymous>)
    at /Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/@swc/core/index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/@swc/core/index.js:30:12)
    at Compiler.parse (/Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/@swc/core/index.js:115:16)
    at Object.parse (/Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/@swc/core/index.js:320:21)
    at /Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:33:19
    at Array.map (<anonymous>)
    at parseBundleAsts (/Users/fabiensevestre/Documents/GitHub/parsec-cloud/oxidation/client/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:31:78)
```

**Comment by FirelightFlagboy** [comment]
I've reformatted the issue body using code block (`` ``` ``) to make it easier to read

**Comment by FirelightFlagboy** [comment]
That seems strange to me to directly call `npm exec -- vite build`, what where you trying to achieve ?

Why do you not use the scripts provided in `package.json` ?

**Comment by fabienSvtr** [comment]
We tried to figure out where the error was for the command: `npm run electron:open` so we ran the command line it contains in `package.json`: 
`npm run electron:copy` && `npx cap open @capacitor-community/electron`

The command `npm run electron:copy` is a shortcut for: 
'npm run native:build` && `npx cap copy @capacitor-community/electron`

so I tried `npm run native:build`and the output was:
`> parsec@0.0.0 native:build`
`> node ./scripts/vite_build_for_native.cjs`
`>>>  npm exec -- vite build`

That's why we tried the 'npm exec -- vite build` command line, to understand where was the error.

I don't know if it's clear, let me know if it's not.

**Comment by FirelightFlagboy** [comment]
This issue was solve by enabling the developer tools on MacOS and 

```shell
sudo mkdir -p /usr/local/bin
sudo cp -v /usr/bin/python3 /usr/local/bin/python # replacing `cp` by `ln` would be best but I didn't achieve to make it work
```

**Comment by FirelightFlagboy** [comment]
I'll close this issue since it's resolved
