### ISSUE TITLE
[:bug:] Flaky testbed server because of concurrency bootstrap of organization

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#4806]
## Description 

The rust test that rely on the testbed server can't fail sometime because multiple tests tries to initialize the same organization (organization with the same name)

## Steps to reproduce

On my left terminal, I start the testbed server:

```shell
poetry run python ./make.py i
poetry run python server/tests/scripts/run_testbed_server.py
```

On my right terminal, I launch the rust tests:

```shell
export TESTBED_SERVER_URL='parsec://127.0.0.1:6770?no_ssl=true'
cargo test -p libparsec_client_connection # I'm able to have that error on that crate, it's also present when I run the tests for the whole workspace
```

## Trace

<details>

<summary>Testbed server trace</summary>

```log
/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py:165: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  self, error: Union[Exception, trio.MultiError]
2023-07-04T13:00:52.393321Z [info     ] Running on http://127.0.0.1:6770 (CTRL + C to quit)
/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py:160: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  except (Exception, trio.MultiError) as error:
/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py:167: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  if isinstance(error, trio.MultiError):
/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py:136: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  except trio.MultiError as error:
2023-07-04T13:00:54.766733Z [error    ] Exception on request POST /testbed/new/minimal 
Traceback (most recent call last):
  File "/home/[REDACTED]/Documents/parsec-cloud/server/tests/scripts/run_testbed_server.py", line 90, in test_new
    template_org_id, template_crc = template_id_to_org_id_and_crc[template]
KeyError: 'minimal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py", line 133, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py", line 161, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py", line 176, in handle_user_exception
    return await super().handle_user_exception(error)
  File "/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart/app.py", line 1107, in handle_user_exception
    raise error
  File "/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart_trio/app.py", line 159, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/[REDACTED]/.cache/pypoetry/virtualenvs/parsec-cloud-JDyud10L-py3.9/lib/python3.9/site-packages/quart/app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/[REDACTED]/Documents/parsec-cloud/server/tests/scripts/run_testbed_server.py", line 100, in test_new
    template_org_id = await backend.test_load_template(template_content)
  File "/home/[REDACTED]/Documents/parsec-cloud/server/parsec/backend/app.py", line 134, in test_load_template
    await self.organization.bootstrap(
  File "/home/[REDACTED]/Documents/parsec-cloud/server/parsec/backend/memory/organization.py", line 125, in bootstrap
    raise OrganizationAlreadyBootstrappedError()
parsec.backend.organization.OrganizationAlreadyBootstrappedError
2023-07-04T13:00:54.770443Z [info     ] 127.0.0.1:41304 POST /testbed/new/minimal 1.1 500 265o 18167us -
2023-07-04T13:00:54.770776Z [info     ] 127.0.0.1:41290 POST /testbed/new/minimal 1.1 200 15o 18950us -
2023-07-04T13:00:54.771738Z [info     ] 127.0.0.1:41316 POST /testbed/new/minimal 1.1 200 15o 3506us -
2023-07-04T13:00:54.772461Z [info     ] 127.0.0.1:41308 POST /testbed/new/coolorg 1.1 200 13o 19791us -
2023-07-04T13:00:54.785721Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=d6dca6ee73734017ba694ef6ec9d115a device_id=alice@dev1 organization_id=Org1
2023-07-04T13:00:54.786969Z [info     ] 127.0.0.1:41330 POST /authenticated/Org1 1.1 200 20o 2403us alice@dev1
2023-07-04T13:00:54.788361Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=3bb7221c388949a6af96e1a4018076b9 device_id=alice@dev1 organization_id=Org2
2023-07-04T13:00:54.791195Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=51b2f12d5ad8433197f4669aa5b5e385 device_id=bob@dev1 organization_id=Org3
2023-07-04T13:00:54.792020Z [info     ] 127.0.0.1:41344 POST /authenticated/Org2 1.1 200 54o 4635us alice@dev1
2023-07-04T13:00:54.793184Z [info     ] 127.0.0.1:41346 POST /authenticated/Org3 1.1 200 25o 3896us bob@dev1
2023-07-04T13:00:54.793980Z [info     ] 127.0.0.1:41352 POST /authenticated/Org1 1.1 401 0o 2238us alice@dev1
2023-07-04T13:00:54.797812Z [info     ] Invited client successfully connected (client/server API version: 4.0/4.0) conn_id=3a71642d6bb94a25851ea88afbc21107 invitation_token=InvitationToken(c0f1bdd1-17dd-40c5-8200-7eef67db0a00) organization_id=Org2
2023-07-04T13:00:54.798264Z [info     ] 127.0.0.1:41290 POST /testbed/drop/Org1 1.1 200 0o 2767us -
2023-07-04T13:00:54.798801Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=5a4a28ebe5d740858421671a205282e1 device_id=bob@dev1 organization_id=Org3
2023-07-04T13:00:54.799973Z [info     ] 127.0.0.1:41376 POST /invited/Org2 1.1 200 20o 3370us -
2023-07-04T13:00:54.800385Z [info     ] 127.0.0.1:41346 POST /authenticated/Org3 1.1 200 23o 2885us bob@dev1
2023-07-04T13:00:54.802044Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=13c7252a9ebb4d41b3f9682173ea675c device_id=bob@dev1 organization_id=Org3
2023-07-04T13:00:54.802925Z [info     ] 127.0.0.1:41346 POST /authenticated/Org3 1.1 200 23o 2026us bob@dev1
2023-07-04T13:00:54.803961Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=557acdaa29f744c08ad5179d32904be8 device_id=bob@dev1 organization_id=Org3
2023-07-04T13:00:54.805651Z [info     ] 127.0.0.1:41346 POST /authenticated/Org3 1.1 200 23o 2315us bob@dev1
2023-07-04T13:00:54.806098Z [info     ] 127.0.0.1:41384 POST /invited/Org2 1.1 404 0o 1289us -
2023-07-04T13:00:54.807338Z [info     ] Authenticated client successfully connected (client/server API version: 4.0/4.0) conn_id=4dca04c15ab04292836e97b13716df81 device_id=bob@dev1 organization_id=Org3
2023-07-04T13:00:54.808174Z [info     ] 127.0.0.1:41346 POST /authenticated/Org3 1.1 200 23o 1708us bob@dev1
2023-07-04T13:00:54.810243Z [info     ] 127.0.0.1:41316 POST /testbed/drop/Org2 1.1 200 0o 1410us -
2023-07-04T13:00:54.813352Z [info     ] 127.0.0.1:41400 GET /authenticated/Org3/events 1.1 401 0o 969us alice@dev1
2023-07-04T13:00:54.815914Z [info     ] 127.0.0.1:41308 POST /testbed/drop/Org3 1.1 200 0o 897us -
```

</details>

**Comment by touilleMan** [comment]
fixed in #4942
