### ISSUE TITLE
`test_about_modal` fail with timeout 

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5042]
Happen during the CI run <https://github.com/Scille/parsec-cloud/actions/runs/5921471877/job/16054074943?pr=5040>

<details>

<summary>test_about_modal.ts Stacktrace</summary>

```
  Running:  test_about_modal.ts                                                            (1 of 16)
PLATFORM environ variable not set, defaulting to `web`
PLATFORM environ variable not set, defaulting to `web`


  Check about modal
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

[@vue/compiler-sfc] `defineEmits` is a compiler macro and no longer needs to be imported.

    1) "before each" hook for "Opens the settings dialog"
    2) "after each" hook for "Opens the settings dialog"


  0 passing (6s)
  2 failing

  1) Check about modal
       "before each" hook for "Opens the settings dialog":
     CypressError: `cy.then()` timed out after waiting `4000ms`.

Your callback function returned a promise that never resolved.

The callback function was:

async (windowElem) => {
      const window = windowElem;
      const [libparsec, nextStage] = window.nextStageHook();
      const configPath = await libparsec.testNewTestbed(template, TESTBED_SERVER_URL);
      assert.isDefined(configPath);
      await nextStage(configPath, "en-US");
      return configPath;
    }

https://on.cypress.io/then

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Check about modal`
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:145251:83)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:13866:41)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=tests/e2e/support/index.ts:692:85)

  2) Check about modal
       "after each" hook for "Opens the settings dialog":
     CypressError: `cy.get()` could not find a registered alias for: `@configPath`.
Available aliases are: `consoleLog, consoleError, window`.

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Check about modal`
      at $Cy.aliasNotFoundFor (http://localhost:8080/__cypress/runner/cypress_runner.js:140235:74)
      at $Cy.getAlias (http://localhost:8080/__cypress/runner/cypress_runner.js:140178:12)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:148512:21)
      at Object.subjectFn (http://localhost:8080/__cypress/runner/cypress_runner.js:159523:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:8080/__cypress/runner/cypress_runner.js:140576:31)
      at onRetry (http://localhost:8080/__cypress/runner/cypress_runner.js:159514:15)
      at retryQuery (http://localhost:8080/__cypress/runner/cypress_runner.js:159527:10)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:159677:17)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromiseCtx (http://localhost:8080/__cypress/runner/cypress_runner.js:16773:10)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:13455:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=tests/e2e/support/index.ts:710:10)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      1                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     test_about_modal.ts                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

</details>

**Comment by FirelightFlagboy** [comment]
Another failure: https://github.com/Scille/parsec-cloud/actions/runs/6082990548/job/16501947168

<details><summary>Details</summary>

```txt
   Running:  test_about_modal.ts                                                            (1 of 18)
PLATFORM environ variable not set, defaulting to `web`
PLATFORM environ variable not set, defaulting to `web`


  Check about modal
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

[@vue/compiler-sfc] `defineEmits` is a compiler macro and no longer needs to be imported.

    1) "before each" hook for "Opens the settings dialog"
    2) "after each" hook for "Opens the settings dialog"


  0 passing (6s)
  2 failing

  1) Check about modal
       "before each" hook for "Opens the settings dialog":
     CypressError: `cy.then()` timed out after waiting `4000ms`.

Your callback function returned a promise that never resolved.

The callback function was:

async (windowElem) => {
      const window = windowElem;
      const [libparsec, nextStage] = window.nextStageHook();
      const configPath = await libparsec.testNewTestbed(template, TESTBED_SERVER_URL);
      assert.isDefined(configPath);
      await nextStage(configPath, "en-US");
      return configPath;
    }

https://on.cypress.io/then

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Check about modal`
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:145251:83)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:13866:41)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=tests/e2e/support/index.ts:696:14)

  2) Check about modal
       "after each" hook for "Opens the settings dialog":
     CypressError: `cy.get()` could not find a registered alias for: `@configPath`.
Available aliases are: `consoleLog, consoleError, window`.

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Check about modal`
      at $Cy.aliasNotFoundFor (http://localhost:8080/__cypress/runner/cypress_runner.js:140235:74)
      at $Cy.getAlias (http://localhost:8080/__cypress/runner/cypress_runner.js:140178:12)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:148512:21)
      at Object.subjectFn (http://localhost:8080/__cypress/runner/cypress_runner.js:159523:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:8080/__cypress/runner/cypress_runner.js:140576:31)
      at onRetry (http://localhost:8080/__cypress/runner/cypress_runner.js:159514:15)
      at retryQuery (http://localhost:8080/__cypress/runner/cypress_runner.js:159527:10)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:159677:17)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromiseCtx (http://localhost:8080/__cypress/runner/cypress_runner.js:16773:10)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:13455:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=tests/e2e/support/index.ts:710:10)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      1                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     5 seconds                                                                        │
  │ Spec Ran:     test_about_modal.ts                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

</details>

**Comment by FirelightFlagboy** [comment]
To re-open is the issue come back
