### ISSUE TITLE
Flake testbed server ? or libparsec_client_connection::cmds::authenticated ?

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5065]
https://github.com/Scille/parsec-cloud/actions/runs/5976941144/job/16215863125

<details>

<summary>Test <code>libparsec_client_connection::cmds authenticated</code> failure starttrace</summary>

```
[2023-08-25T14:17:36Z INFO  libparsec_testbed::scope] Using already started testbed server at parsec://localhost:6777?no_ssl=true
[2023-08-25T14:17:36Z DEBUG reqwest::connect] starting new connection: http://localhost:6777/
thread 'authenticated' panicked at 'Bad response status from testbed server: Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(6777), path: "/testbed/new/minimal", query: None, fragment: None }, status: 500, headers: {"content-type": "text/html; charset=utf-8", "content-length": "265", "access-control-allow-origin": "*", "access-control-allow-methods": "*", "access-control-allow-headers": "*", "date": "Fri, 25 Aug 2023 14:17:36 GMT", "server": "parsec/v2.16.0-a.0+dev"} }', /home/runner/work/parsec-cloud/parsec-cloud/libparsec/crates/testbed/src/env.rs:287:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: libparsec_testbed::env::test_new_testbed::{{closure}}
   3: libparsec_testbed::scope::TestbedScope::start::{{closure}}
   4: libparsec_testbed::scope::TestbedScope::run_with_server::{{closure}}
   5: cmds::authenticated::authenticated::{{closure}}
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
   9: tokio::runtime::scheduler::current_thread::Context::enter
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
  11: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::context::set_scheduler::{{closure}}
  14: std::thread::local::LocalKey<T>::try_with
  15: std::thread::local::LocalKey<T>::with
  16: tokio::runtime::context::set_scheduler
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  19: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
  20: tokio::runtime::context::runtime::enter_runtime
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  22: tokio::runtime::runtime::Runtime::block_on
  23: cmds::authenticated::authenticated
  24: cmds::authenticated
  25: cmds::authenticated::{{closure}}
  26: core::ops::function::FnOnce::call_once
  27: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
```

<details>

**Comment by mmmarcos** [comment]
This seems still relevant: https://github.com/Scille/parsec-cloud/actions/runs/6170390465/job/16746598658

Here's a similar failure stacktrace for the anonymous (instead of authenticated) case.
<details>
<summary>Test libparsec_client_connection::cmds anonymous failure stacktrace</summary>

```
[2023-09-13T09:13:54Z INFO  libparsec_testbed::scope] Using already started testbed server at parsec://localhost:6777?no_ssl=true
[2023-09-13T09:13:54Z DEBUG reqwest::connect] starting new connection: http://localhost:6777/
thread 'anonymous' panicked at 'Bad response status from testbed server: Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(6777), path: "/testbed/new/minimal", query: None, fragment: None }, status: 500, headers: {"content-type": "text/html; charset=utf-8", "content-length": "265", "access-control-allow-origin": "*", "access-control-allow-methods": "*", "access-control-allow-headers": "*", "date": "Wed, 13 Sep 2023 09:13:54 GMT", "server": "parsec/v2.16.0-a.0+dev"} }', /home/runner/work/parsec-cloud/parsec-cloud/libparsec/crates/testbed/src/env.rs:287:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: libparsec_testbed::env::test_new_testbed::{{closure}}
   3: libparsec_testbed::scope::TestbedScope::start::{{closure}}
   4: libparsec_testbed::scope::TestbedScope::run_with_server::{{closure}}
   5: cmds::anonymous::{{closure}}::anonymous::{{closure}}
   6: cmds::anonymous::{{closure}}
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
  11: tokio::runtime::scheduler::current_thread::Context::enter
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
  13: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  14: tokio::runtime::context::scoped::Scoped<T>::set
  15: tokio::runtime::context::set_scheduler::{{closure}}
  16: std::thread::local::LocalKey<T>::try_with
  17: std::thread::local::LocalKey<T>::with
  18: tokio::runtime::context::set_scheduler
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
  22: tokio::runtime::context::runtime::enter_runtime
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  24: tokio::runtime::runtime::Runtime::block_on
  25: cmds::anonymous
  26: cmds::anonymous::{{closure}}
  27: core::ops::function::FnOnce::call_once
  28: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

   Canceling due to test failure: 1 tests still running
        PASS [   0.105s] libparsec_client_connection::cmds authenticated
        PASS [   0.126s] libparsec_client_connection::cmds authenticated_sse
------------
     Summary [   1.100s] 26/1319 tests run: 25 passed, 1 failed, 0 skipped
        FAIL [   0.074s] libparsec_client_connection::cmds anonymous
error: test run failed
Error: Process completed with exit code 100.
```
</details>
