### ISSUE TITLE
[🐛 | Bug]: Testbed crash because of shamir

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5209]
### Version

v2.16.0-rc.4-dev.2023-09-14-sha.bd59600

### What platforms you were running our software when the bug happened ?

Web

### What happened ?

I used the testbed image `ghcr.io/scille/parsec-cloud/parsec-testbed-server:v2.16.0-rc.4-dev.2023-09-14-sha.bd59600`

and started the ionic web dev server and the web apps paniced

### Relevant output

Log in browser:

```
panicked at 'Bad response status from testbed server: Response { status: 500, headers: {"content-length": "265", "content-type": "text/html; charset=utf-8"} }', /[redacted]/parsec-cloud/libparsec/crates/testbed/src/env.rs:287:13
```

Log in docker:

```
Traceback (most recent call last):
  File "/testbed/venv/lib/python3.9/site-packages/quart_trio/app.py", line 133, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/testbed/venv/lib/python3.9/site-packages/quart_trio/app.py", line 161, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/testbed/venv/lib/python3.9/site-packages/quart_trio/app.py", line 176, in handle_user_exception
    return await super().handle_user_exception(error)
  File "/testbed/venv/lib/python3.9/site-packages/quart/app.py", line 1107, in handle_user_exception
    raise error
  File "/testbed/venv/lib/python3.9/site-packages/quart_trio/app.py", line 159, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/testbed/venv/lib/python3.9/site-packages/quart/app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/testbed/run_testbed_server.py", line 152, in test_new
    backend.test_duplicate_organization(template_org_id, new_org_id)
  File "/testbed/venv/lib/python3.9/site-packages/parsec/backend/app.py", line 119, in test_duplicate_organization
    self.shamir.test_duplicate_organization(id, new_id)  # type: ignore[attr-defined]
AttributeError: 'MemoryShamirComponent' object has no attribute 'test_duplicate_organization'
```

**Comment by vxgmichel** [comment]
Fixed a while ago

**Comment by FirelightFlagboy** [comment]
Can you recall the PR/commit that fixed this issue to link it to this issue ?
