### ISSUE TITLE
[🐛 | Bug]: `parsec.cli` crash with `No module named 'parsec._parsec'`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5483]
### Version

v2.16.0-rc.5

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

I cannot use `parsec.cli` to create an organization, it fail with a missing module `parsec._parsec`

### Relevant output

```
parsec.cli core create_organization --help
Traceback (most recent call last):
  File "/snap/parsec/266/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/snap/parsec/266/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/andesite/Documents/parsec-cloud-2.16/parsec/__init__.py", line 18, in <module>
    __import__("parsec.utils")
  File "/home/andesite/Documents/parsec-cloud-2.16/parsec/utils.py", line 14, in <module>
    from parsec._parsec import DateTime
ModuleNotFoundError: No module named 'parsec._parsec'
```

**Comment by FirelightFlagboy** [comment]
The path `/[redacted]/parsec-cloud-2.16` if the path where I cloned the repo `parsec-cloud` at the branch `releases/2.16` feels like a confinement issue for python :thinking:

**Comment by FirelightFlagboy** [comment]
Affect the old v2, closing as no longer maintained
