### ISSUE TITLE
GUI crash

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#563]
J'ai vidé mon cache local, puis ai relancé Parsec. Il a freezé peu de temps après, les clics ne répondait plus, beaucoup de dirty blocs sont apparus, et ce crash est survenu.
```
2019-07-03 13:53:58 [info     ] Request                        [parsec.api.transport] cmd=realm_get_roles conn_id=a25c8a01c82d43c6a998bf17760fa01d device_id=francois@laptop
2019-07-03 13:53:58 [info     ] Stopping fuse thread...        [parsec.core.mountpoint.fuse_runner] mountpoint=PosixPath('/home/rossigneux/parsec_mnt/Test')
2019-07-03 13:53:58 [info     ] Fuse thread stopped            [parsec.core.mountpoint.fuse_runner] mountpoint=PosixPath('/home/rossigneux/parsec_mnt/Test')
2019-07-03 13:53:58 [debug    ] Send event                     [parsec.event_bus] event_name=mountpoint.stopped mountpoint=PosixPath('/home/rossigneux/parsec_mnt/Test')
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/central_widget.py", line 176, in show_mount_widget
    mount_widget = MountWidget(self.core, self.jobs_ctx, self.event_bus, parent=self)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/mount_widget.py", line 32, in __init__
    self.show_workspaces_widget()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/mount_widget.py", line 62, in show_workspaces_widget
    self.workspaces_widget.reset()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/workspaces_widget.py", line 301, in reset
    core=self.core,
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 150, in submit_job
    self._portal.run(_submit_job)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_threads.py", line 105, in run
    return self._do_it(self._run_cb, afn, *args)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_threads.py", line 86, in _do_it
    return q.get().unwrap()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_threads.py", line 59, in unprotected_afn
    return await afn(*args)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 147, in _submit_job
    await self._send_job_channel.send(job)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_channel.py", line 144, in send
    self.send_nowait(value)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_ki.py", line 165, in wrapper
    return fn(*args, **kwargs)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_channel.py", line 129, in send_nowait
    raise _core.BrokenResourceError
trio.BrokenResourceError
2019-07-03 13:53:58 [exception] Uncatched error                [parsec.core.gui.trio_thread] 
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 65, in _run_fn
    self.ret = await self._fn(*self._args, **self._kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/main_window.py", line 47, in _do_run_core
    qt_on_ready.emit(core, core_jobs_ctx)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 124, in _start
    await nursery.start(job._run_fn)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 95, in _run_fn
    signal.emit(self)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 32, in emit
    QMetaObject.invokeMethod(self.qobj, self.signal_name, Qt.QueuedConnection, *cooked_args)
RuntimeError: wrapped C/C++ object of type WorkspacesWidget has been deleted
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 65, in _run_fn
    self.ret = await self._fn(*self._args, **self._kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/main_window.py", line 47, in _do_run_core
    qt_on_ready.emit(core, core_jobs_ctx)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 124, in _start
    await nursery.start(job._run_fn)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 95, in _run_fn
    signal.emit(self)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 32, in emit
    QMetaObject.invokeMethod(self.qobj, self.signal_name, Qt.QueuedConnection, *cooked_args)
RuntimeError: wrapped C/C++ object of type WorkspacesWidget has been deleted
2019-07-03 13:53:58 [error    ] Unhandled error                [parsec.core.gui.main_window] 
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 65, in _run_fn
    self.ret = await self._fn(*self._args, **self._kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/main_window.py", line 47, in _do_run_core
    qt_on_ready.emit(core, core_jobs_ctx)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 124, in _start
    await nursery.start(job._run_fn)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 95, in _run_fn
    signal.emit(self)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 32, in emit
    QMetaObject.invokeMethod(self.qobj, self.signal_name, Qt.QueuedConnection, *cooked_args)
parsec.core.gui.trio_thread.JobResultError: crashed
```

**Comment by frossigneux** [comment]
Autre erreur lors de l'essai suivant:
```
2019-07-03 14:00:05 [warning  ] Tried to remove a dirty block that doesn't exist anymore [parsec.core.local_storage] 
2019-07-03 14:00:05 [warning  ] Tried to remove a dirty block that doesn't exist anymore [parsec.core.local_storage] 
2019-07-03 14:00:05 [debug    ] Sending keep alive ping        [parsec.api.transport] conn_id=309430dda8204aa790df0f14d0f092fa device_id=francois@laptop
2019-07-03 14:00:05 [info     ] Request                        [parsec.api.transport] cmd=block_create conn_id=a7894bd7f7b34df7b96b1c35f14fc4e6 device_id=francois@laptop
2019-07-03 14:00:05 [debug    ] Send event                     [parsec.event_bus] event_name=fs.entry.updated id=EntryID('df2003e8-dd2d-4d73-8023-fe9fcb1e8fb4') workspace_id=EntryID('7209ff67-cde9-41ad-b421-792ff4d03a45')
2019-07-03 14:00:05 [info     ] Stopping fuse thread...        [parsec.core.mountpoint.fuse_runner] mountpoint=PosixPath('/home/rossigneux/parsec_mnt/Test')
2019-07-03 14:00:05 [debug    ] Send event                     [parsec.event_bus] event_name=fs.entry.updated id=EntryID('df2003e8-dd2d-4d73-8023-fe9fcb1e8fb4') workspace_id=EntryID('7209ff67-cde9-41ad-b421-792ff4d03a45')
2019-07-03 14:00:05 [info     ] Fuse thread stopped            [parsec.core.mountpoint.fuse_runner] mountpoint=PosixPath('/home/rossigneux/parsec_mnt/Test')
2019-07-03 14:00:05 [debug    ] Send event                     [parsec.event_bus] event_name=mountpoint.stopped mountpoint=PosixPath('/home/rossigneux/parsec_mnt/Test')
2019-07-03 14:00:05 [exception] Uncatched error                [parsec.core.gui.trio_thread] 
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 51, in _next_ws_event
    return next(self._ws_events)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 65, in _run_fn
    self.ret = await self._fn(*self._args, **self._kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/main_window.py", line 47, in _do_run_core
    qt_on_ready.emit(core, core_jobs_ctx)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/logged_core.py", line 101, in logged_core_factory
    root_nursery.cancel_scope.cancel()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 188, in backend_listen_events
    await backend_events_manager.run(task_status=task_status)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 67, in run
    await self._event_listener_manager()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 85, in _event_listener_manager
    await trio.sleep_forever()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 145, in _event_pump
    await self._event_pump_do(cmds)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 149, in _event_pump_do
    rep = await cmds.events_listen()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/porcelain.py", line 40, in wrapper
    return await cmd(transport, *args, **kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/cmds.py", line 120, in events_listen
    transport, events_listen_serializer, keepalive=wait, cmd="events_listen", wait=wait
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/cmds.py", line 82, in _send_cmd
    raw_rep = await transport.recv(keepalive)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 142, in recv
    event = await self._next_ws_event()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 55, in _next_ws_event
    await self._net_recv()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 68, in _net_recv
    self.ws.receive_bytes(None)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/wsproto/connection.py", line 231, in receive_bytes
    raise ValueError('Connection already closed.')
ValueError: Connection already closed.
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 51, in _next_ws_event
    return next(self._ws_events)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 65, in _run_fn
    self.ret = await self._fn(*self._args, **self._kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/main_window.py", line 47, in _do_run_core
    qt_on_ready.emit(core, core_jobs_ctx)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/logged_core.py", line 101, in logged_core_factory
    root_nursery.cancel_scope.cancel()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 188, in backend_listen_events
    await backend_events_manager.run(task_status=task_status)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 67, in run
    await self._event_listener_manager()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 85, in _event_listener_manager
    await trio.sleep_forever()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 145, in _event_pump
    await self._event_pump_do(cmds)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 149, in _event_pump_do
    rep = await cmds.events_listen()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/porcelain.py", line 40, in wrapper
    return await cmd(transport, *args, **kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/cmds.py", line 120, in events_listen
    transport, events_listen_serializer, keepalive=wait, cmd="events_listen", wait=wait
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/cmds.py", line 82, in _send_cmd
    raw_rep = await transport.recv(keepalive)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 142, in recv
    event = await self._next_ws_event()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 55, in _next_ws_event
    await self._net_recv()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 68, in _net_recv
    self.ws.receive_bytes(None)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/wsproto/connection.py", line 231, in receive_bytes
    raise ValueError('Connection already closed.')
ValueError: Connection already closed.
2019-07-03 14:00:05 [error    ] Unhandled error                [parsec.core.gui.main_window] 
Traceback (most recent call last):
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/trio_thread.py", line 65, in _run_fn
    self.ret = await self._fn(*self._args, **self._kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/gui/main_window.py", line 47, in _do_run_core
    qt_on_ready.emit(core, core_jobs_ctx)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/logged_core.py", line 101, in logged_core_factory
    root_nursery.cancel_scope.cancel()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 188, in backend_listen_events
    await backend_events_manager.run(task_status=task_status)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 67, in run
    await self._event_listener_manager()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 85, in _event_listener_manager
    await trio.sleep_forever()
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 145, in _event_pump
    await self._event_pump_do(cmds)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/event_listener.py", line 149, in _event_pump_do
    rep = await cmds.events_listen()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/porcelain.py", line 40, in wrapper
    return await cmd(transport, *args, **kwargs)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/cmds.py", line 120, in events_listen
    transport, events_listen_serializer, keepalive=wait, cmd="events_listen", wait=wait
  File "/home/rossigneux/Projects/parsec-cloud/parsec/core/backend_connection/cmds.py", line 82, in _send_cmd
    raw_rep = await transport.recv(keepalive)
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 142, in recv
    event = await self._next_ws_event()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 55, in _next_ws_event
    await self._net_recv()
  File "/home/rossigneux/Projects/parsec-cloud/parsec/api/transport.py", line 68, in _net_recv
    self.ws.receive_bytes(None)
  File "/home/rossigneux/.virtualenvs/parsec/lib/python3.6/site-packages/wsproto/connection.py", line 231, in receive_bytes
    raise ValueError('Connection already closed.')
parsec.core.gui.trio_thread.JobResultError: crashed

```
