### ISSUE TITLE
Inconsistent date formatting

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#583]
Two gui tests fail on my machine because of date formatting issue:
- `tests/core/gui/test_devices.py::test_device_info`
- `tests/core/gui/test_users.py::test_device_info`

The CI seems fine with it though. 

```
______________________________________ test_device_info ______________________________________

value = <trio._core._run.Nursery object at 0x7efc25bcce80>

    async def yield_(value=None):
>       return await _yield_(value)

../miniconda/envs/parsec/lib/python3.7/site-packages/async_generator/_impl.py:106: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../miniconda/envs/parsec/lib/python3.7/site-packages/async_generator/_impl.py:99: in _yield_
    return (yield _wrap(value))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

aqtbot = <tests.core.gui.conftest.AsyncQtBot object at 0x7efc25bccf28>
running_backend = AppServer(entry_point=<bound method BackendApp.handle_client of <parsec.backend.app.BackendApp object at 0x7efc0c5b635...', connection_factory=<function server_factory.<locals>._server_factory.<locals>.connection_factory at 0x7efc200562f0>)
autoclose_dialog = <tests.core.gui.conftest.autoclose_dialog.<locals>.DialogSpy object at 0x7efc25b6d4e0>
logged_gui = <parsec.core.gui.main_window.MainWindow object at 0x7efc25ad8d38>

    @pytest.mark.gui
    @pytest.mark.trio
    async def test_device_info(aqtbot, running_backend, autoclose_dialog, logged_gui):
        d_w = logged_gui.test_get_devices_widget()
        assert d_w is not None
        async with aqtbot.wait_signal(d_w.list_success):
            pass
        assert d_w.layout_devices.count() == 2
        item = d_w.layout_devices.itemAt(0)
        item.widget().show_device_info()
        item = d_w.layout_devices.itemAt(1)
        item.widget().show_device_info()
>       assert autoclose_dialog.dialogs == [
            ("Information", "dev1\n\nCreated on 01/01/00 00:00:00"),
            ("Information", "dev2\n\nCreated on 01/01/00 00:00:00"),
        ]
E       AssertionError: assert [('Informatio...12:00:00 AM')] == [('Information...00 00:00:00')]
E         At index 0 diff: ('Information', 'dev1\n\nCreated on 01/01/2000 12:00:00 AM') != ('Information', 'dev1\n\nCreated on 01/01/00 00:00:00')
E         Full diff:
E         - [('Information', 'dev1\n\nCreated on 01/01/2000 12:00:00 AM'),
E         ?                                            -   ^^^      ---
E         + [('Information', 'dev1\n\nCreated on 01/01/00 00:00:00'),
E         ?                                              + ^
E         -  ('Information', 'dev2\n\nCreated on 01/01/2000 12:00:00 AM')]
E         ?                                            -   ^^^      ---
E         +  ('Information', 'dev2\n\nCreated on 01/01/00 00:00:00')]
E         ?                                              + ^

tests/core/gui/test_devices.py:62: AssertionError
------------------------------------ Captured Qt messages ------------------------------------
    QtWarningMsg: QObject::setParent: Cannot set parent, new parent is in a different thread
    QtWarningMsg: QObject::setParent: Cannot set parent, new parent is in a different thread
------------------------------------ Captured stderr call ------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/trio/testing/_trio_test.py", line 30, in wrapper
    partial(fn, **kwargs), clock=clock, instruments=instruments
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/trio/_core/_run.py", line 1444, in run
    raise runner.main_task_outcome.error
  File "/home/vinmic/parsec-cloud/tests/core/gui/conftest.py", line 125, in outer_wrapper
    _qt_thread_gateway.run_action_pump()
  File "/home/vinmic/parsec-cloud/tests/core/gui/conftest.py", line 52, in run_action_pump
    raise value
  File "/home/vinmic/parsec-cloud/tests/core/gui/conftest.py", line 105, in inner_wrapper
    ret = await fn(**kwargs)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/pytest_trio/plugin.py", line 343, in _bootstrap_fixtures_and_run_test
    raise trio.MultiError(test_ctx.error_list)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/pytest_trio/plugin.py", line 191, in _fixture_manager
    await yield_(nursery_fixture)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/async_generator/_impl.py", line 106, in yield_
    return await _yield_(value)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/async_generator/_impl.py", line 99, in _yield_
    return (yield _wrap(value))
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.7/site-packages/pytest_trio/plugin.py", line 245, in run
    await self._func(**resolved_kwargs)
  File "/home/vinmic/parsec-cloud/tests/core/gui/test_devices.py", line 62, in test_device_info
    assert autoclose_dialog.dialogs == [
AssertionError: assert [('Informatio...12:00:00 AM')] == [('Information...00 00:00:00')]
  At index 0 diff: ('Information', 'dev1\n\nCreated on 01/01/2000 12:00:00 AM') != ('Information', 'dev1\n\nCreated on 01/01/00 00:00:00')
  Full diff:
  - [('Information', 'dev1\n\nCreated on 01/01/2000 12:00:00 AM'),
  ?                                            -   ^^^      ---
  + [('Information', 'dev1\n\nCreated on 01/01/00 00:00:00'),
  ?                                              + ^
  -  ('Information', 'dev2\n\nCreated on 01/01/2000 12:00:00 AM')]
  ?                                            -   ^^^      ---
  +  ('Information', 'dev2\n\nCreated on 01/01/00 00:00:00')]
  ?  
```

**Comment by touilleMan** [comment]
fixed by #585
