### ISSUE TITLE
UnboundLocalError when extracting a realm export

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#6368]
When running `parsec backend sequester extract_realm_export`:
```python
/: Workspace manifest loaded
/: Extracting folder...
Error: local variable 'child_manifest' referenced before assignment
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/sequester_export_reader.py", line 255, in extract_children
    child_manifest = self.load_manifest(child_id)
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/sequester_export_reader.py", line 191, in load_manifest
    raise InconsistentWorkspaceError(
parsec.sequester_export_reader.InconsistentWorkspaceError: Cannot retrieve workspace manifest: vlob 514183eefaed4e088df26e32c5d54f71 doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/bin/parsec", line 8, in <module>
    sys.exit(cli())
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/cli.py", line 45, in patched_cli_main
    return vanilla_cli_main(args=args_list[:], **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/backend/cli/sequester.py", line 810, in extract_realm_export
    for fs_path, event_type, event_msg in extract_workspace(
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/sequester_export_reader.py", line 391, in extract_workspace
    yield from wksp.extract_workspace(output=output)
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/sequester_export_reader.py", line 371, in extract_workspace
    yield from self.extract_children(
  File "/app/.heroku/python/lib/python3.9/site-packages/parsec/sequester_export_reader.py", line 275, in extract_children
    f"Vlob {child_id.hex} version {child_manifest.version}: {exc}",
UnboundLocalError: local variable 'child_manifest' referenced before assignment
```
Can be reproduced as such:
- sequester service not configured
- create workspace
- create and synchronize file
- configure a sequester service
- create and synchronize file
- export realm
- run `extract_realm_export` command

**Comment by mmmarcos** [comment]
@vxgmichel should this be fixed for v2.17?
