### ISSUE TITLE
[🐛 | Bug]: `version_updater.py`: Multiple license fields found in package.json

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#7209]
### Parsec version tested on:

master

### Platforms tested on:

Any

### Bug description:

https://github.com/Scille/parsec-cloud/actions/runs/8872422983/job/24356745681?pr=7204

### Relevant output:

```shell
$ python misc/version_updater.py --tool parsec --version 3.0.0-b.6.dev.19842+948eb11
Refreshing npm lock file /home/runner/work/parsec-cloud/parsec-cloud/client/package-lock.json ...
Traceback (most recent call last):
  File "/home/runner/work/parsec-cloud/parsec-cloud/misc/version_updater.py", line 514, in <module>
    errors += check_tool(tool, update=not args.check).errors
  File "/home/runner/work/parsec-cloud/parsec-cloud/misc/version_updater.py", line 481, in check_tool
    update_res.updated |= tool.post_update_hook(update_res.updated)
  File "/home/runner/work/parsec-cloud/parsec-cloud/misc/version_updater.py", line 83, in post_update_hook
    updated |= refresh_npm_package_lock(updated_files)
  File "/home/runner/work/parsec-cloud/parsec-cloud/misc/version_updater.py", line 141, in refresh_npm_package_lock
    assert found_license_count <= 1, "Multiple license fields found in package.json"
AssertionError: Multiple license fields found in package.json
```

**Comment by mmmarcos** [comment]
Done in #7230
