### ISSUE TITLE
Unhandled (and unexpected !) HandshakeRVKMismatch exception

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#767]
```
[parsec.zip](https://github.com/Scille/parsec-cloud/files/3789151/parsec.zip)
[parsec.zip](https://github.com/Scille/parsec-cloud/files/3789152/parsec.zip)
{"cmd": "new_instance", "rep_status": "ok", "event": "Command processed", "logger": "parsec.core.ipcinterface", "level": "info", "timestamp": "2019-10-30 10:47:23"}
{"conn_id": "96b987aa50fd4712a6d9c13ed78806b4", "auth": "<anonymous>", "cmd": "organization_bootstrap", "event": "Request", "logger": "parsec.api.transport", "level": "info", "timestamp": "2019-10-30 10:47:38"}
{"conn_id": "33fccac3c7064cd1b9b19d4ba376355b", "auth": "<anonymous>", "cmd": "organization_bootstrap", "event": "Request", "logger": "parsec.api.transport", "level": "info", "timestamp": "2019-10-30 10:48:12"}
{"task_name": "trio._highlevel_serve_listeners._run_handler", "duration": 0.2181086540222168, "stack": "", "event": "Task step took too long", "logger": "parsec.monitoring", "level": "warning", "timestamp": "2019-10-30 10:49:17"}
{"task_name": "trio._highlevel_serve_listeners._run_handler", "duration": 0.21788859367370605, "stack": "", "event": "Task step took too long", "logger": "parsec.monitoring", "level": "warning", "timestamp": "2019-10-30 10:49:24"}
{"event": "Starting UI", "logger": "parsec.core.gui.app", "level": "info", "timestamp": "2019-10-30 10:49:37"}
{"cmd": "new_instance", "rep_status": "ok", "event": "Command processed", "logger": "parsec.core.ipcinterface", "level": "info", "timestamp": "2019-10-30 10:49:37"}
{"event": "Try to connect to backend...", "logger": "parsec.core.backend_connection.event_listener", "level": "info", "timestamp": "2019-10-30 10:51:17"}
{"conn_id": "f24693db73d5431dbfb6cabc925ebe8e", "reason": "HandshakeRVKMismatch('Root verify key for organization `{self.organization_id}` differs between client and server',)", "event": "Handshake failed", "logger": "parsec.api.transport", "level": "warning", "timestamp": "2019-10-30 10:51:17"}
{"event": "Cannot connect to the backend", "logger": "parsec.core.backend_connection.event_listener", "level": "exception", "timestamp": "2019-10-30 10:51:17"}

Traceback (most recent call last):

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 140, in _do_handshake

    handshake.process_result_req(result_req)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\api\protocol\handshake.py", line 304, in process_result_req

    raise HandshakeRVKMismatch(data["help"])

parsec.api.protocol.handshake.HandshakeRVKMismatch: Root verify key for organization `{self.organization_id}` differs between client and server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\event_listener.py", line 63, in _event_listener_manager

    await nursery.start(self._event_pump)

  File "C:\Program Files (x86)\Parsec\site-packages\trio\_core\_run.py", line 622, in start

    old_nursery.start_soon(thunk, *args, name=name)

  File "C:\Program Files (x86)\Parsec\site-packages\trio\_core\_run.py", line 506, in __aexit__

    raise combined_error_from_nursery

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\event_listener.py", line 121, in _event_pump

    await cmds.events_subscribe()

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\porcelain.py", line 41, in wrapper

    async with self.transport_pool.acquire() as transport:

  File "C:\Program Files (x86)\Parsec\site-packages\async_generator\_util.py", line 34, in __aenter__

    return await self._agen.asend(None)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 239, in acquire

    keepalive=self.keepalive,

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 106, in _connect

    await _do_handshake(transport, handshake)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 156, in _do_handshake

    raise BackendHandshakeError(exc) from exc

parsec.core.backend_connection.exceptions.BackendHandshakeError: Root verify key for organization `{self.organization_id}` differs between client and server

{"task_name": "parsec.core.backend_connection.event_listener.backend_listen_events", "duration": 0.54150390625, "stack": null, "event": "Task step took too long", "logger": "parsec.monitoring", "level": "warning", "timestamp": "2019-10-30 10:51:18"}
{"conn_id": "6a77a19f246d4d40bd7047eb19ec95fd", "reason": "HandshakeRVKMismatch('Root verify key for organization `{self.organization_id}` differs between client and server',)", "event": "Handshake failed", "logger": "parsec.api.transport", "level": "warning", "timestamp": "2019-10-30 10:51:18"}
{"event": "Uncatched error", "logger": "parsec.core.gui.trio_thread", "level": "exception", "exception": "Traceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 140, in _do_handshake\n    handshake.process_result_req(result_req)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\api\\protocol\\handshake.py\", line 304, in process_result_req\n    raise HandshakeRVKMismatch(data[\"help\"])\nparsec.api.protocol.handshake.HandshakeRVKMismatch: Root verify key for organization `{self.organization_id}` differs between client and server\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\trio_thread.py\", line 98, in _run_fn\n    result = await self._fn(*self._args, **self._kwargs)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\users_widget.py\", line 107, in _do_list_users\n    users = await core.user_fs.backend_cmds.user_find()\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\porcelain.py\", line 41, in wrapper\n    async with self.transport_pool.acquire() as transport:\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\async_generator\\_util.py\", line 34, in __aenter__\n    return await self._agen.asend(None)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 239, in acquire\n    keepalive=self.keepalive,\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 106, in _connect\n    await _do_handshake(transport, handshake)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 156, in _do_handshake\n    raise BackendHandshakeError(exc) from exc\nparsec.core.backend_connection.exceptions.BackendHandshakeError: Root verify key for organization `{self.organization_id}` differs between client and server", "timestamp": "2019-10-30 10:51:18"}

Traceback (most recent call last):

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 140, in _do_handshake

    handshake.process_result_req(result_req)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\api\protocol\handshake.py", line 304, in process_result_req

    raise HandshakeRVKMismatch(data["help"])

parsec.api.protocol.handshake.HandshakeRVKMismatch: Root verify key for organization `{self.organization_id}` differs between client and server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\trio_thread.py", line 98, in _run_fn

    result = await self._fn(*self._args, **self._kwargs)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\users_widget.py", line 107, in _do_list_users

    users = await core.user_fs.backend_cmds.user_find()

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\porcelain.py", line 41, in wrapper

    async with self.transport_pool.acquire() as transport:

  File "C:\Program Files (x86)\Parsec\site-packages\async_generator\_util.py", line 34, in __aenter__

    return await self._agen.asend(None)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 239, in acquire

    keepalive=self.keepalive,

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 106, in _connect

    await _do_handshake(transport, handshake)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 156, in _do_handshake

    raise BackendHandshakeError(exc) from exc

parsec.core.backend_connection.exceptions.BackendHandshakeError: Root verify key for organization `{self.organization_id}` differs between client and server

{"conn_id": "bf3ab2da1e92477391e39beb156bfac0", "reason": "HandshakeRVKMismatch('Root verify key for organization `{self.organization_id}` differs between client and server',)", "event": "Handshake failed", "logger": "parsec.api.transport", "level": "warning", "timestamp": "2019-10-30 10:51:18"}
{"event": "Uncatched error", "logger": "parsec.core.gui.trio_thread", "level": "exception", "exception": "Traceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 140, in _do_handshake\n    handshake.process_result_req(result_req)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\api\\protocol\\handshake.py\", line 304, in process_result_req\n    raise HandshakeRVKMismatch(data[\"help\"])\nparsec.api.protocol.handshake.HandshakeRVKMismatch: Root verify key for organization `{self.organization_id}` differs between client and server\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\remote_devices_manager.py\", line 138, in get_user_and_devices\n    user_id\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\porcelain.py\", line 41, in wrapper\n    async with self.transport_pool.acquire() as transport:\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\async_generator\\_util.py\", line 34, in __aenter__\n    return await self._agen.asend(None)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 239, in acquire\n    keepalive=self.keepalive,\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 106, in _connect\n    await _do_handshake(transport, handshake)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\backend_connection\\transport.py\", line 156, in _do_handshake\n    raise BackendHandshakeError(exc) from exc\nparsec.core.backend_connection.exceptions.BackendHandshakeError: Root verify key for organization `{self.organization_id}` differs between client and server\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\trio_thread.py\", line 98, in _run_fn\n    result = await self._fn(*self._args, **self._kwargs)\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\gui\\devices_widget.py\", line 74, in _do_list_devices\n    current_device.user_id\n  File \"C:\\Program Files (x86)\\Parsec\\site-packages\\parsec\\core\\remote_devices_manager.py\", line 154, in get_user_and_devices\n    ) from exc\nparsec.core.remote_devices_manager.RemoteDevicesManagerError: Failed to fetch user `Thierry2` from the backend: Root verify key for organization `{self.organization_id}` differs between client and server", "timestamp": "2019-10-30 10:51:18"}

Traceback (most recent call last):

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\transport.py", line 140, in _do_handshake

    handshake.process_result_req(result_req)

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\api\protocol\handshake.py", line 304, in process_result_req

    raise HandshakeRVKMismatch(data["help"])

parsec.api.protocol.handshake.HandshakeRVKMismatch: Root verify key for organization `{self.organization_id}` differs between client and server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\remote_devices_manager.py", line 138, in get_user_and_devices

    user_id

  File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\backend_connection\porcelain.py", line 41, in wrapper

    async with self.transport_pool.acquire() as transport:

  File "C:\Program Files (x86)\Parsec\site-packages\async_generator\_util.py", li...</anonymous></anonymous>
```

On top of that, windows explorer freeze when doing a right click inside a workspace mountpoint

**Comment by touilleMan** [comment]
Test with Scille4_Scille4#Thierry4@DESKTOP-B8BBS1N (password: %_'Q&)3RoMg]S[.Kt/Ecr+"VA) device on the enclosed data

[parsec.zip](https://github.com/Scille/parsec-cloud/files/3789243/parsec.zip)

**Comment by c4ffein** [comment]
Handled the core exceptions in https://github.com/Scille/parsec-cloud/pull/856
Will now investigate mismatch from backend

**Comment by c4ffein** [comment]
Found no RVK matching client one in backend DB, backend DB key for this organization doesn't seem linked to the client one through permutations (as in the case with little / big endians errors)

**Comment by c4ffein** [comment]
Investigating the code multiple times, found no probable cause. There has been some changes since this bug has been reported, so closing this issue for now.
