### ISSUE TITLE
E2E test `Opens the create organization modal` is flaky

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#7766]
```
[chromium] › create_organization.spec.ts:6:1 › Opens the create organization modal ────────────

    Error: Element does not have a 'disabled' attribute.

      29 |   await expect(nextButton).toHaveText('Continue');
      30 |   await modal.locator('.server-choice-item').nth(0).click();
    > 31 |   await expect(nextButton).toBeTrulyDisabled();
         |                            ^
      32 |
      33 |   // Check if the close button closes the modal
      34 |   await expect(modal.locator('.closeBtn')).toBeVisible();

        at /home/runner/work/parsec-cloud/parsec-cloud/client/tests/pw/e2e/create_organization.spec.ts:31:28

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Error: Element does not have a 'disabled' attribute.

      29 |   await expect(nextButton).toHaveText('Continue');
      30 |   await modal.locator('.server-choice-item').nth(0).click();
    > 31 |   await expect(nextButton).toBeTrulyDisabled();
         |                            ^
      32 |
      33 |   // Check if the close button closes the modal
      34 |   await expect(modal.locator('.closeBtn')).toBeVisible();

        at /home/runner/work/parsec-cloud/parsec-cloud/client/tests/pw/e2e/create_organization.spec.ts:31:28

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/create_organization-Opens-the-create-organization-modal-chromium-retry1/trace.zip
    Usage:

        npx playwright show-trace test-results/create_organization-Opens-the-create-organization-modal-chromium-retry1/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

    Retry #2 ───────────────────────────────────────────────────────────────────────────────────────

    Error: Element does not have a 'disabled' attribute.

      29 |   await expect(nextButton).toHaveText('Continue');
      30 |   await modal.locator('.server-choice-item').nth(0).click();
    > 31 |   await expect(nextButton).toBeTrulyDisabled();
         |                            ^
      32 |
      33 |   // Check if the close button closes the modal
      34 |   await expect(modal.locator('.closeBtn')).toBeVisible();

        at /home/runner/work/parsec-cloud/parsec-cloud/client/tests/pw/e2e/create_organization.spec.ts:31:28
```

https://github.com/Scille/parsec-cloud/actions/runs/10059916187/job/27806261176?pr=7735

**Comment by Max-7** [comment]
Looked at recent CI runs, didn't see this test being flaky so we're probably fine.
