### ISSUE TITLE
[🐛 | Bug]: Error on check certificate from auto-updater

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#9165]
### Parsec version tested on:

3.2.0

### Platforms tested on:

Windows

### Bug description:

 https://scille.sentry.io/issues/6129207433/?project=4507638897246208&referrer=project-issue-stream

### Relevant output:

```
Unhandled Promise Rejection
Error: New version 3.2.2-rc.1 is not signed by the application owner: publisherNames: Scille, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=Certum Extended Validation Code Signing 2021 CA, O=Asseco Data Systems S.A., C=PL",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1828360533000)/",
    "NotBefore": "/Date(1733752534000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "6B1C7DAC8B40616EAB3E19CF74420ED9",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "5D56476E12C6DB8055CB37D8EA98E9A9D0B01091",
    "Version": 3,
    "Issuer": "CN=Certum Extended Validation Code Signing 2021 CA, O=Asseco Data Systems S.A., C=PL",
    "Subject": "CN=SCILLE, O=SCILLE, STREET=11 Chemin de Jales, PostalCode=33160, L=Saint-M�dard-en-Jalles, S=Nouvelle-Aquitaine, C=FR, SERIALNUMBER=799854633, OID.1.3.6.1.4.1.311.60.2.1.1=Bordeaux, OID.1.3.6.1.4.1.311.60.2.1.2=Nouvelle-Aquitaine, OID.1.3.6.1.4.1.311.60.2.1.3=FR, OID.2.5.4.15=Private Organization"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=/"DigiCert, Inc./", C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(2079647999000)/",
    "NotBefore": "/Date(1727308800000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0BAE66BC5ABA7F9587C6F9E904E33304",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp 2024, O=DigiCert, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "DBD385EE62DBD23E7BE4F67148508724D5865B45",
    "Version": 3,
    "Handle": 2258965501552,
    "Issuer": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=/"DigiCert, Inc./", C=US",
    "Subject": "CN=DigiCert Timestamp 2024, O=DigiCert, C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature v�rifi�e.",
  "Path": "[C://Users//jerom//AppData//Local//parsec-updater//pending//temp-Parsec_3.2.2-rc.1_win_x86_64.exe](file:///C://Users//jerom//AppData//Local//parsec-updater//pending//temp-Parsec_3.2.2-rc.1_win_x86_64.exe)"
}
    at newError (D:/Programmes/parsec3/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/error.js:5:19)
    at Object.task (D:/Programmes/parsec3/resources/app.asar/node_modules/electron-updater/out/NsisUpdater.js:56:63)
    at async NsisUpdater.executeDownload (D:/Programmes/parsec3/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:562:13)
```

**Comment by Max-7** [comment]
Should be fixed be #9164
